# The LWK Viewer user manual (English), as blocks - build_manual.py turns it into a .docx.

from blocks import *

TITLE = "LWK Viewer User Manual"

DOC = [
    BLANK(),
    H1('LWK Viewer User Manual'),
    P('Oct 4, 2026 · @Wilson · for viewer version 2026-10-08'),
    H2('What the LWK Viewer is'),
    P("The LWK Viewer shows a project's Revit sheets and 3D model in a web browser, so anyone on the team can review, measure, mark up and raise issues without Revit. It runs on desktop, iPad and iPhone, and every issue raised is shared live with the whole team and can be picked up back in Revit."),
    P("Around the drawings and the model it also holds the team's work: a list of projects, task lists (in place of Lark Tasks), whiteboards and a messenger, all linked to the same sheets, 3D views and issues, with one search across all of them."),
    LABEL('Who it is for'),
    TABLE(['Who', 'Typical use'], [
        ['Architects and designers', 'Check drawings and the 3D model, raise design and coordination issues, answer issues assigned to them'],
        ['Project leads and directors', 'Review progress on a tablet, follow open and overdue issues on the Dashboard'],
        ['BIM coordinators', 'Publish models and sheets from Revit, run nightly exports, manage issues from inside Revit'],
        ['Consultants and site staff (Viewer role)', 'Look and read only, on any device'],
        ['Team leads', 'Plan the team\'s task lists, follow who does what by when, discuss in project channels'],
        ['Project and site admins', 'Add people, set roles, manage projects'],
    ]),
    LABEL('What you can do'),
    UL([
        '**Sheets (2D):** open every published sheet as a sharp PDF, search the words on all drawings, mark up with 20+ tools, compare with earlier versions, and export PDFs with markups.',
        '**3D:** orbit, pan and walk through the model and its links, cut floor plans and sections, measure with snapping, check element properties, and save views.',
        '**Issues:** raise an issue on a sheet or in 3D with a snapshot, assign it, set a due date, comment with @mentions, and track it to closure. Issues exchange with Revit, Navisworks and BIMcollab through BCF.',
        '**2D + 3D side by side:** click a plan on a sheet and the 3D view goes there; walk in 3D and see where you are on the plan.',
        '**Revit link:** the LWK Issues window in Revit lists the same issues, zooms to them and sends replies back.',
        '**Projects:** every job with its people, drawings, model, tasks, issues, files and chat on one page.',
        '**Tasks:** team task lists with List, Kanban, Gantt and Dashboard views, imported from Lark and linked to issues, sheets and 3D views.',
        '**Board:** a shared whiteboard per project for notes, mind maps and sketches.',
        '**Messenger:** project channels, group chats and direct messages, with task and issue updates posted in, links to tasks, issues, sheets and 3D, and messages to and from WhatsApp.',
        '**Issues and tasks together:** make a task from an issue; finishing one offers to close the other.',
        '**Revit elements:** a 3D issue keeps its Revit ElementId, ready for Select by ID, BCF and the LWK add-in.',
        '**Search:** one box (Ctrl+K) for tasks, issues, sheets, 3D views, messages and file links.',
        '**Offline:** download a project to a tablet and keep working on site with no signal.',
    ]),
    H2('Before you start'),
    P("You need an account, a supported browser and the viewer's web address; nothing is installed on your computer."),
    LABEL('Your account'),
    UL([
        'An admin creates your account and sends you an invitation with a **temporary password**.',
        'Open the viewer address, sign in with your **Email** and the temporary password, then choose your own password (at least 8 characters) on the **My account** page that opens.',
        'You stay signed in for 30 days on each browser. After 10 wrong passwords in 15 minutes the sign-in pauses for 15 minutes.',
        'Your role is set per project: **Project admin**, **Member** or **Viewer** (see For admins). A Viewer sees a banner saying they can look and read but not change anything.',
    ]),
    P('**Viewer address:** [paste the viewer address here before sending]'),
    LABEL('Browsers and devices'),
    TABLE(['Device', 'Browser', 'Notes'], [
        ['Windows or Mac', 'Chrome or Edge (recommended), Safari, Firefox', 'A mouse with a middle button (wheel) makes 3D much easier'],
        ['iPad', 'Safari', 'Apple Pencil works for markup; landscape recommended'],
        ['iPhone', 'Safari', 'Best for looking and reading; 3D loads a lighter copy of the model'],
    ]),
    LABEL('Confidentiality'),
    UL([
        'Treat the viewer like the project folder: only people on the project team should be added.',
        'Do not share your password, forward invitation emails, or post links outside the team.',
        'Screenshots and exported PDFs follow the same rules as any other project document.',
    ]),
    H2('How it fits together'),
    P('A BIM coordinator publishes sheets and 3D from Revit; the team reviews in the browser; issues go back to the modeller inside Revit.'),
    IMG(),
    P('LWK Viewer workflow · publish, review, answer in Revit'),
    OL([
        '**Publish.** In Revit, **Publish to Viewer** exports the chosen sheets as PDF and the model (with its links) in a fast 3D format, then uploads only the files that changed. It can repeat every night.',
        '**Prepare.** The server makes a lighter copy of each 3D model for phones and tablets, and reads the text on every sheet so it can be searched. This takes a few minutes after each upload.',
        '**Review.** The team opens Sheets, 3D or the Dashboard in any browser. Markups and issues save automatically and appear for everyone.',
        '**Answer.** The person assigned sees the issue in the viewer, and also in Revit through the **LWK Issues** window, which zooms to it and sends replies and status changes back.',
        '**Close.** The author or a project admin marks the issue Resolved and then Closed. The Dashboard tracks what is open, overdue and who holds it.',
    ]),
    P('Around this loop, the work itself is planned in **Tasks** (a task can be made from an issue and closes it when done), discussed in **Messenger** (each project has a channel where task and issue updates appear) and found again with **Search**. The **Projects** page ties each job together.'),
    H2('Quick start: your first ten minutes'),
    P('Sign in, open a sheet, look at the same place in 3D, and raise one test issue.'),
    OL([
        '**Sign in.** Open the viewer address, enter your email and password, and change the temporary password when asked.',
        '**Pick the project.** Use the project name at the top (a drop-down appears when you are on more than one project), or pick it on the **Dashboard**.',
        '**Open a sheet.** On **Sheets**, click a sheet in the left list, or type a room name, grid or note in **Search all sheets**. Scroll to zoom, hold the middle mouse button to pan, press **Fit** to see the whole sheet.',
        '**Go to 3D.** Click **3D** at the top left. Hold the right mouse button to orbit, the middle button to pan, and scroll to zoom. Double-click a surface to zoom in on it.',
        '**Look at a floor.** Choose a level in the **Floor plan** drop-down: the model is cut 1.2 m above that floor and seen from the top. **Page Up / Page Down** step between floors; **Whole building** goes back to 3D.',
        '**Click an element** to see its properties in the **Selection** panel on the right.',
        '**Raise a test issue.** Click **Add issue**, click a surface, type a title such as "TEST - please ignore", then **Save issue**. It appears in **Issues in 3D** for everyone.',
        '**Try 2D + 3D.** Back on Sheets, open a plan and press **2D + 3D**; click on the plan and the 3D view moves there.',
        '**Make a task from it.** Open the test issue, press **+ New task from this issue**, check the list, owner and due date, then **Make the task**.',
        '**Say hello in Chat.** Open **Chat**, pick the project\'s channel, type **#** and pick your test task, then press **Send**.',
        '**Search.** Press **Ctrl+K** (or the magnifier at the top) and type a word from your issue title: the issue, the task and your message are all found.',
        '**Delete your test issue and task** when you are done: the issue from its detail window (**Delete**), the task from its window (the bin button).',
    ]),
    H2('Dashboard and projects'),
    P("The Dashboard is the project's issue scoreboard: how many are open, overdue, who holds them and what changed this week."),
    LABEL('Getting around'),
    UL([
        'The top bar on every page has the same pages in the same place: **Projects**, **Sheets**, **3D**, **Board**, **Tasks**, **Chat** (with the number of unread messages) and **Dashboard**. On the right: the **Search** magnifier, **+ Task** (on Sheets and 3D: keeps this sheet or 3D view on a task), **Admin** (admins only), **Account** and **Sign out**. On a phone the top bar scrolls sideways.',
        'The **project drop-down** (Sheets, 3D, Board, Dashboard) lists the project names from the Projects page, e.g. "SKW · HKA-P-01681-ARC". A project made of several models, such as MOS Site 1 and Site 2, appears as a group with its parts under it.',
        'The connection chip shows **online - your name**, **N waiting to save** (the connection dropped; your changes are queued and sent when it returns), or **offline**. Do not reload the page while changes are waiting: the queue is kept only until you leave the page.',
    ]),
    LABEL('What the Dashboard shows'),
    TABLE(['Part', 'What it tells you'], [
        ['Filters', '**Closed within** (Any time to Last 12 months), **Type**, **Assigned to**, **Office**, **Only mine**, **Include "not an issue"**'],
        ['This week', 'Issues raised, closed, open and overdue this week, and open issues by person; **Send to Teams** posts it to the project channel'],
        ['Summary figures', 'Issues, Open, In progress, Resolved, Closed, Overdue, Due in 7 days, Unassigned, Avg days open, Avg days to close'],
        ['Charts', 'Raised and closed by week (last 12 weeks), by status, type, priority, where raised (sheet or 3D) and office'],
        ['Responsibility table', "Each assignee's open, in progress, overdue and due-soon counts, oldest open issue and last activity; click a row to filter"],
        ['Lists', '**Overdue**, **Due in the next 14 days**, **Recently changed**, **Going quiet** (untouched for 14 days or more)'],
    ]),
    UL([
        '**Export CSV** downloads the filtered issues for Excel. **Report** opens a printable issue report with pictures.',
        'The page refreshes itself every 2 minutes; **Refresh** updates it now.',
        '**Tasks of this project:** when the project is on the Projects page, the Dashboard also shows its tasks from every team\'s list: open, overdue and sub-tasks done.',
    ]),
    LABEL('Notifications'),
    UL([
        "**Email** (when the server's mail is set up): you are emailed when you are made owner of a task, when someone @mentions you in a task or a chat, and when a task you follow gets a comment or is completed; once a day you also get your tasks due tomorrow and overdue.",
        "**Teams:** if an admin has connected the project's Teams channel, it posts there when an issue is raised, assigned, changes status or due date, or gets a comment. @mentions in comments become Teams mentions.",
        'A weekly summary can be posted to the same Teams channel (Monday by default).',
        "**Messenger:** the project's channel shows new tasks, assignments, completions and comments, and new or changed issues, as cards.",
    ]),
    H2('Projects'),
    P('The **Projects** page lists the team\'s jobs, each with its people, drawings, model, tasks, issues, files and chat in one place. It is for reading; admins set projects up on **Admin > Projects and members** (the **Manage** button takes you there).'),
    LABEL('The list'),
    TABLE(['Column', 'Shows'], [
        ['Project', 'Its short name and code, e.g. SKW · HKA-P-01681-ARC'],
        ['Open', '**Sheets**, **3D** and **Dashboard** buttons. A project made of several models (MOS Site 1, Site 2) shows a small menu of its parts on each button'],
        ['Tasks', 'Progress (done of all), overdue tasks and the open tasks, from every team\'s list that has a group for this project'],
        ['Issues', 'A bar of the issues by status, with open / total; overdue in red. Added up over all the project\'s models'],
        ['Folders', 'Its OneDrive, SharePoint or ACC folders'],
        ['Chat', 'The project\'s channel in the Messenger, with unread messages'],
    ]),
    UL([
        'Search projects or people, and filter by status, at the top.',
        'Click a row for the **details**: members by team, issues by status (click a figure to open the Dashboard), the tasks with their sub-tasks, and **Models and sheets**: each part with its own Sheets, 3D and Dashboard links.',
        '**One project, several models.** A job exported as several Revit models and sheet sets stays one project with several parts. Its members are everyone on any part, its issue counts add up all the parts, and the project drop-downs show it as a group.',
    ]),
    H2('Tasks'),
    P('**Tasks** are the team\'s task lists, in place of Lark Tasks, linked to the drawings, the model and the issues.'),
    H3('Lists, groups and views'),
    UL([
        '**Task lists** belong to a team (for example LWK-MANILA). Inside a list the **groups** are usually the jobs (SKW, Kai Tak 2A3 ...). A group linked to a project shows **Project**, **Sheets** and **Dashboard** buttons; link them in **...** > **Groups and projects**.',
        '**Quick access** on the left: **Owned** (open tasks that are yours), **Subscribed**, **All**, **Created**, **Assigned** (by you to others) and **Completed**, across every list you can see. **People** shows the organisation by team, office or company, with each person\'s open and overdue tasks.',
        '**List:** a grouped table. Edit in place, open sub-tasks with ▸, drag rows to reorder or move them to another group. A task with linked issues shows **#2 open** until they are all resolved, then **#✓**.',
        '**Kanban:** cards in columns; drag a card to another column. The board fills the window, so the sideways scroll bar is always at the bottom of the screen; **Shift + mouse wheel**, dragging an empty part of the board, or the **‹ ›** buttons at its edges also scroll it.',
        '**Gantt:** bars on a timeline; drag a bar, or drag its ends to change the dates. Each change asks **Change the dates?** first: **Save** keeps it, **Cancel** puts the bar back (tick **Don\'t ask again today** to skip the question on this device). The legend explains the colours; milestones are gold.',
        '**Dashboard:** total, completed, incomplete and overdue, by owner, by project, average duration and due soon. **Activities:** everything that changed, by whom.',
        'Filter by owner and priority, sort, **Group by**, and **Customize** which columns show. Lists can have their own columns (person, select, text, date, number), for example Modelers and Project Manager.',
    ]),
    H3('A task'),
    UL([
        'Click a task to open its window: title, **Owners**, start and due **Dates**, **Group**, **Priority** and the list\'s own columns. **Mark complete** finishes it.',
        '**Completion method:** **OR** = done when any owner completes it; **AND** = every owner completes their own part.',
        '**Sub-tasks:** type in **+ Add sub-task** and press Enter. A sub-task can have sub-tasks of its own, as in Lark, up to 5 levels: open the sub-task and add them there, or use the **+** that shows on a row in the List. Drop a task on the right half of another task\'s title to make it its sub-task. Deleting a task deletes everything under it (**Ctrl+Z** brings it all back).',
        '**Linked issues** show their status now (Open, In progress, Resolved). **+ Link an issue** picks one of the project\'s issues.',
        '**Files, sheets and 3D views:** paste a OneDrive, SharePoint or ACC address, or use **+ Task** on the Sheets or 3D page to keep the sheet or view you are looking at. Revit elements kept on a task show as **Elements to change**.',
        '**Comments:** @name tells someone; paste a screenshot or attach files (up to 50 MB each). Your own comments have **edit** and **delete**.',
        '**Follow** emails you when the task changes; **Share** sends it to a chat; the link button copies its address.',
        'The ▲ ▼ buttons, or **K** / **J**, go to the previous / next task. On a phone, **Back** returns to the list.',
    ]),
    H3('Members of a list'),
    UL([
        '**Owner** (changes the list\'s settings and members), **Editor** (adds and changes tasks) and **Viewer** (reads only). Site admins see every list.',
    ]),
    H3('Importing from Lark'),
    OL([
        'In Lark, open the task list and choose **...** > **Export** (Excel).',
        'In Tasks, use **+** > **Import a Lark task list (.xlsx)** to make a new list, or **...** > **Import from Lark (.xlsx) / CSV** to bring it into the open list.',
        'Groups, sub-tasks, owners, followers, dates, done status, priority, completion method, milestones, Modelers and Project Manager all come in, with a link back to each task in Lark.',
        'Importing the same export again updates the tasks instead of adding them twice. Names with no account yet are kept as names; once the accounts exist, use **...** > **Match names to accounts**.',
    ]),
    H2('Board'),
    P('**Board** is a shared whiteboard for each project, in the manner of Miro: sticky notes, text, shapes, connectors, mind maps, pictures and frames, with templates to start from. Everyone on the project sees changes as they are made. Pick the project at the top; use the board list to make, rename, copy or delete boards.'),
    H2('Messenger'),
    P('**Chat** opens the Messenger: the team\'s conversations, next to the work they are about.'),
    LABEL('Kinds of chat'),
    TABLE(['Chat', 'What it is'], [
        ['Project channel', 'One per project. Everyone on the project is in it. New tasks, assignments, completions, task comments and new or changed issues are posted into it as cards'],
        ['Topic', 'A sub-channel of a project channel for one subject (Facade, MEP coordination, Site visits). Listed under its channel, and as tabs under the channel\'s name: **# General** is the channel itself'],
        ['Group', 'Any group of people, named by whoever starts it'],
        ['Direct message', 'Two people'],
        ['Task discussion', 'The comments of the tasks you follow, answered from here'],
    ]),
    UL([
        'The pencil at the top starts a new chat. Right-click a chat (or hold it on a phone) for **Details**, **Mark as read**, **New topic** (project channels), **Leave**, **Import WhatsApp chat ...**, **Send chat link to WhatsApp** and **Delete chat**, for those who may delete it.',
        '**Opening a topic:** anyone in the project channel presses **+ Topic** on the tabs under its name (or **New topic** in its menu, or the pencil > **Topic in a project channel**). Everyone in the channel is added.',
        '**Who can delete a chat:** a direct message, either of the two people (it goes for both); a group, its admins (who started it) or a site admin; a project channel or topic, the project\'s admins or a site admin. Deleting a channel deletes its topics too.',
        '**Chat info** (the people button): the description, the members (add, remove, message), **Pictures and files**, **Leave this chat** and **Delete this chat**.',
        'The number on **Chat** in the top bar of every page shows unread messages; **@** means you were mentioned.',
    ]),
    LABEL('Writing'),
    UL([
        '**Enter** makes a new line; the **Send** button sends (on a keyboard, **Ctrl+Enter** sends too).',
        'Paste or drop screenshots, or use the paper clip for pictures and files up to 50 MB each. OneDrive, SharePoint and ACC links show as cards; a video link shows a play card, and a pasted OneDrive or SharePoint **Embed** code plays right in the chat.',
        '**@** a person. **#** a task, **!** an issue, **$** a sheet, **%** the 3D model or a saved view: a list opens as you type. **Choose the project first** in the row of projects at the top of the list (in a project channel its own project is chosen). The **#** button beside the paper clip opens the same lists with tabs.',
        'The picked item shows in the message as a named link that opens it.',
        '🙂 adds emoji.',
        '**Formatting (Aa):** the box shows the words as they will be sent, as in Lark. **Aa** shows the format buttons: **B**, **S**, **I**, **U**, numbered and bulleted lists, quote, link, code and block of code; **Ctrl+B**, **Ctrl+I**, **Ctrl+U** and **Ctrl+Shift+X** work on the selection. On a phone they appear in their own row after **Aa**. Forwarded to WhatsApp, a message keeps its bold, italic and strikethrough.',
        '**The buttons under the box:** **Aa**, 🙂 emoji, **@** a person, **#** a task, issue, sheet or 3D view (it shows in the box as a chip), the paper clip, **+** and **Send**, which is always on screen, on a phone too.',
        '**The + button:** **Poll**, **Event / meeting**, **Task**, or a link to a task, issue, sheet or 3D view.',
    ]),
    LABEL('Polls, events and tasks'),
    UL([
        '**Poll:** a question with 2 to 10 choices; tick **Allow more than one answer**, **Anonymous** or a closing date if you like. Tap a choice to vote, again to take it back. The writer can **Close poll** (and reopen it).',
        '**Event:** title, date, time (or **All day**), where and the Teams link. Everyone in the chat is invited (by email too when mail is set up) and answers **Going**, **Maybe** or **Can\'t go**. **Add to calendar (.ics)** puts it in Outlook, Google or the phone. The writer can **Change** or **Cancel event**; the chat is told.',
        '**Task:** choose the task list and group (this project\'s first), owners (this chat\'s people first), due date and priority. The task goes into the list and its card into the chat. ⋯ More > **Make a task** on any message does the same, with the message as the description, the people @mentioned as owners and a link back to it.',
    ]),
    LABEL('A message'),
    UL([
        'Hover a message (tap it on a phone): 🙂 **React**, ↩ **Reply**, ✏ **Edit** (your own) and ⋯ **More**: **Copy**, **Pin**, **Make a task**, **Forward to another chat**, **Send to WhatsApp**, **Copy link to this message** and **Delete** (your own).',
        '**Edit** changes the message in place: **Ctrl+Enter** saves, **Esc** cancels; others see "(edited)". **Edit** and **Delete** are only for the person who sent the message (not the chat\'s admin, not a site admin); others see "message deleted".',
        '**Pinned messages:** anyone in the chat can pin a message, up to 100 a chat. The bar under the chat\'s name shows the latest one; click it to see the message and move on to the next; **All** lists them, with **unpin**.',
        '**Reactions** show under the message with a count; tap one to add or take away yours.',
        'A message that could not be sent stays with **send again**.',
    ]),
    LABEL('WhatsApp'),
    UL([
        '**Out:** **Send to WhatsApp** on a message sends its words, links and files. On a phone, pictures go as themselves through the share sheet; on a computer it opens WhatsApp Desktop or WhatsApp Web.',
        '**Copied messages:** messages copied in WhatsApp and pasted into the box are offered as one "From WhatsApp" quote.',
        '**Exported chat:** in WhatsApp, the chat > **More** > **Export chat**, and send yourself the .zip (with media) or .txt. Then in a chat\'s menu choose **Import WhatsApp chat ...**: the messages arrive as one quote with the pictures in place.',
        '**Android:** with the viewer installed as an app, use WhatsApp\'s **Share** > **LWK Viewer** and choose the chat. (iPhone does not offer this: copy and paste, or export.)',
        'There is no automatic two-way link with WhatsApp.',
    ]),
    H2('Calendar'),
    P('**Calendar** shows what is coming up for you, by date: **meetings** sent in the Messenger (with your reply), **your tasks** on their due dates and **issues assigned to you** on their due dates.'),
    UL([
        'A month on a computer, a list on a phone (**Month** / **List**). The tick boxes show or hide meetings, tasks and issues. **‹ ›** and **Today** move through the months; on a phone, swipe.',
        'Click an entry for its details, then open the chat, the task or the issue. Replies to a meeting are made in its chat.',
        '**+ Event:** choose a chat; the event form opens there, so everyone in it is invited.',
        '**Add to Outlook:** **Open in Outlook on this PC** subscribes Outlook to your calendar (choose **Yes**), or copy the address and use Outlook\'s **Add calendar > From Internet**. Outlook then shows the entries beside your own calendar and updates them by itself. Outlook on the web and on phones can only reach it when the viewer is reachable from the internet.',
        'The address is yours alone: **Make a new address** if it was shared by mistake (the old one stops working).',
    ]),
    H2('Notifications and the app'),
    P('New chat messages reach you without reloading any page, and the viewer can be installed as an app.'),
    UL([
        '**While a viewer page is open** (any page, a tab in the background, or the app): new messages show as notifications on Windows, Mac and Android; a click opens the chat at the message. The chat you are looking at stays quiet. The tab title shows the unread count, e.g. **(3) LWK Viewer**, and so does the app\'s icon.',
        '**The bell** in the top bar: **Turn on notifications** (the browser asks once), then choose **Every message**, **@mentions and direct messages** or **Nothing**.',
        '**Mute a chat:** Chat info > **Mute notifications**. A muted chat still tells you when you are @mentioned.',
        '**Install the app:** the bell > **Install the app** (Edge, Chrome), or the install icon at the right of the address bar. On Android: menu > **Add to Home screen**. On iPhone and iPad: Safari > Share > **Add to Home Screen**. The app opens in its own window, with shortcuts to Chat, Tasks, Calendar, Folders and Projects (right-click the icon).',
        '**When no page is open (push):** the bell > **Turn on for this device**. This works when the viewer is opened by its **https** address; ask your admin. Messages then arrive on that phone or computer even with the app closed.',
    ]),
    H2('Undo'),
    UL([
        '**Ctrl+Z** (Cmd+Z on a Mac) undoes the last change; **Ctrl+Y** (or Ctrl+Shift+Z) redoes it. A note at the bottom says what was undone, with **Redo**.',
        '**Tasks:** changed fields, Kanban moves, list drags, Gantt moves, a new task and a deleted task (with its sub-tasks).',
        '**Messenger:** a deleted message (your own, within a day), an edit, a pin and a reaction.',
        '**Folders:** delete, rename, move, upload and a new folder.',
        'While you type in a box, Ctrl+Z undoes the typing as usual. The Sheets and 3D pages keep their own undo for markups.',
    ]),
    H2('Folders'),
    P('**Folders** holds each project\'s files in a folder on the server, like ACC Docs or a shared drive. Pick the project at the top left.'),
    UL([
        '**Browse:** the folder tree on the left, the path at the top, or **Search this project\'s files**. Double-click a folder to open it; click a PDF, picture or video to preview it.',
        '**Upload:** drop files, or whole folders, onto the page (or onto a folder in the list), or press **Upload**. **+ Folder** makes a folder.',
        '**⋯ on a file** (or right-click): Preview, Download, **Add to the Sheets page** (PDFs), **Star**, **Pin for everyone** (project admins), Copy link, Rename, **Move to ...** and Delete. Drag files onto a folder to move them; **Delete** and **F2** work on the selected file.',
        '**Pinned** shows the documents a project admin pinned for everyone; **Starred** shows your own. **Recent** lists the newest files.',
        '**Deleting:** the person who uploaded a file, or a project admin. Deleted things go to **Recently deleted**, from where they can be put back; **Ctrl+Z** also brings them back at once.',
        '**Folder templates (project admins):** ⋯ (top right) > **Save these folders as a template** keeps this project\'s folders (no files) by name. In another project, **Lay out folders from a template** makes the folders it is missing; nothing is deleted.',
        '**To the Sheets page:** a PDF\'s ⋯ > **Add to the Sheets page** turns its pages into sheets in a set of their own (choose the set and the sheet number), ready for markups and issues.',
        'Files put into the project\'s folder on the server some other way (for example from Windows Explorer) show up here too.',
    ]),
    H2('Sheets (2D)'),
    P('The Sheets page shows every published sheet as the real PDF, searchable and ready for markup; markups save by themselves, there is no Save button.'),
    H3('Finding a sheet'),
    UL([
        'The **Sheets** list on the left shows number and name. "x/y mapped" means that many views on the sheet are linked to the 3D model.',
        'Click a sheet to open it. The viewer remembers the last sheet you had open.',
        '**Search all sheets** finds sheet numbers, names and any words printed on the drawings (room names, notes, grid labels). Matches are highlighted on the sheet. The first search on a project can take a moment while the drawings are read.',
        '**Page Down / Page Up** go to the next or previous sheet.',
        'To add an outside PDF (a consultant drawing, a sketch), use the **PDF** upload button and name its **set** (e.g. "Uploaded PDFs" or "Consultant 2026-10"). Each set is its own entry in the drop-down at the top, under the project\'s title, apart from the sheets from Revit. Its sheets show "Imported 2D only" and can be removed with their **✕**.',
    ]),
    H3('Moving around a sheet'),
    TABLE(['Action', 'Mouse', 'iPad / touch'], [
        ['Zoom', 'Scroll wheel (zooms round the pointer)', 'Pinch'],
        ['Pan', 'Hold the middle button, or the **Pan** tool (H)', 'Two fingers; after you use an Apple Pencil, one finger pans'],
        ['Whole sheet', '**Fit**', '**Fit**'],
        ['Rotate the page', 'Rotate button in the toolbar', 'Same'],
        ['Menu', 'Right-click', 'Long press'],
        ['Undo / redo', 'Ctrl+Z / Ctrl+Y', 'Two-finger tap / three-finger tap'],
    ]),
    H3('Useful sheet tools'),
    UL([
        '**Split** opens a second sheet beside the first, with its own zoom.',
        '**Links** turns section marks, callouts and elevation markers into links to their sheets; **← back** returns.',
        '**Compare** shows what changed against an earlier upload of the same sheet, another sheet, or a PDF from your computer: red = removed, green = added. **N / Shift+N** jump between changes.',
        '**2D + 3D** opens the 3D model beside the sheet. Choose **Stand there** or **Look at**, then click a plan: the 3D view goes to that spot. A "you are here" marker on the plan follows the 3D camera; tick **Follow** to keep it in view and switch plans as you walk between floors. Only plan views take part, not sections or elevations.',
    ]),
    H3('Markup tools'),
    TABLE(['Group', 'Tools'], [
        ['Shapes', 'Rect, Circle, Line, Arrow, Cloud, Polyline, Polygon'],
        ['Freehand', 'Pen (hold still at the end of a stroke to snap it to a line, circle or rectangle), Highlighter'],
        ['Text', 'Text, Text box, Callout'],
        ['Stamps', 'APPROVED, APPROVED AS NOTED, REVISE & RESUBMIT, REJECTED, REVIEWED, FOR INFORMATION, VOID (signed with your name and time)'],
        ['Measuring', "Measure, Dimension, Area, Angle (use the scale in the **1:** box, or the view's own scale when it is empty)"],
        ['Other', 'Snip (copies a region as an image; you can also paste an image), Select text, Eraser, Match properties, Select, Pan'],
    ]),
    UL([
        '**Polyline / Polygon:** click the points, then press Enter, double-click or **✓ Finish**. Backspace removes the last point.',
        '**Style bar:** Layer, Line / Fill / Text colour, Opacity, Weight (paper mm), line Type, Font, Size (text height in mm), Align.',
        '**Editing:** select a markup to move, resize or restyle it; R / Shift+R rotate it 90°; Ctrl+C / Ctrl+V copy and paste (paste on another sheet lands at the same spot); Delete removes it.',
        '**Comment or Issue:** the **Comment / Issue** switch in the top bar decides what happens when you finish a markup. In **Issue** mode the **Raise issue** window opens straight away. A comment can be turned into an issue later with **Issue** or right-click **Raise issue**.',
        '**Layers:** markups sit on layers (default "General"). Admins can lock a layer or hide it from some people. The eye button hides all markups.',
    ]),
    H3('Exporting'),
    UL([
        '**PDF** (download) exports this sheet, every sheet with markups, or all sheets, with markups either **Editable** (real PDF comments for Bluebeam, Acrobat or PDF-XChange) or **Flattened**, at 100, 150 or 200 dpi, optionally with an issue report at the end.',
        '**JSON** (download / upload) saves or loads all comments and issues, for backup or moving between projects.',
        '**BCF** exports the sheet issues for Revit or Navisworks (see Issues and BCF).',
    ]),
    H2('3D: moving around'),
    P('The 3D page uses the same mouse as most BIM viewers: right button orbits, middle button pans, wheel zooms, left button picks.'),
    H3('Mouse, touch and keys'),
    TABLE(['Action', 'Mouse', 'iPad / iPhone'], [
        ['Orbit', 'Hold the right button and drag', 'One finger'],
        ['Pan', 'Hold the middle button (wheel) and drag', 'Two fingers'],
        ['Zoom', 'Scroll wheel (towards the pointer)', 'Pinch'],
        ['Focus on a surface', 'Double-click it', 'Double tap'],
        ['Select an element', 'Left click', 'Tap'],
        ['Set the orbit centre', 'Right-click without dragging, or right-click menu **Set orbit centre here**', '-'],
        ['Menu of actions', 'Right-click', '-'],
        ['New issue at a spot', '**Add issue**, then click', 'Long press (0.6 s)'],
        ['Floor above / below', 'Page Up / Page Down', 'Floor plan list'],
        ['Cancel measure or walk', 'Esc', 'Stop button'],
    ]),
    P('With a mouse the view stops exactly where you let go; with a finger it glides a little, as on any tablet app.'),
    H3('Right-click menu'),
    P('On an element: **Set orbit centre here**, **Zoom to this element**, **Isolate**, **Hide**, **Show all**, **Walk from here**, **Add issue here**, **Section on this face**, **Square section box to this face**, **Turn section on/off**, **Measure**, **Save view...**, **Fit model**. On empty space: Show all, Turn section on/off, Measure, Save view..., Fit model.'),
    H3('View cube and camera'),
    UL([
        'Click a **face** of the cube for that view, an **edge** for the view between two faces, a **corner** for an isometric view. Drag the cube to orbit. The ring under it shows north.',
        'The house button returns to the 3D overview. **Fit** frames all loaded models.',
        '**Perspective / Parallel** switches the projection (plans are always parallel).',
        '**Set front:** click a wall to tell the cube which way is "Front" for this building; **World** goes back to the world axes.',
    ]),
    H3('Floors'),
    UL([
        'The **Floor plan** drop-down lists **Whole building** and every level from the top down.',
        'Picking a level cuts the model from 0.5 m below to 1.2 m above that floor and looks straight down, like a Revit plan.',
        '**Page Up / Page Down** step up and down; **Whole building** returns to the full 3D model.',
        "**Drawing** lays that floor's plan sheet over the model, so you can compare drawing and model.",
    ]),
    H3('Models panel'),
    UL([
        'One tick box per model (the host model and each link). Untick to hide a model and free memory; **All on / All off** switch them together and keep your view.',
        '**▸** beside a model shows its size and number of copies, and **Compare with previous export** to see what was added, changed or removed since the last publish.',
        '**Apply link transforms** (on) places links where they sit in Revit.',
        '**Light mode (phones, tablets)** loads repeated typical floors only near where you are looking. It is on by default on phones and tablets.',
        'Every panel heading (Models, Section, Measure, and so on) folds away when clicked, and stays folded next time.',
    ]),
    H2('3D: selecting, finding and display'),
    P('Click any element to see what it is; use the Model browser to find elements by name, type, level or property.'),
    H3('The Selection panel'),
    P("A click shows the element's **Model**, **Category**, **Family / type**, **Level**, **Revit id** (ElementId), **UniqueId**, **IFC GUID**, the clicked **Point** (x, y, z in metres) and **Shared E,N,Z** (survey coordinates), followed by all its Revit parameters in folding groups."),
    UL([
        '**Copy Revit ID** copies the ElementId; in Revit use **Manage > Select by ID** and paste it to select the same element there. **Show in Revit** asks the LWK add-in to select it (see Revit elements). **+ Task** keeps the element on a task.',
        '**Isolate** shows only the selected element(s). **Hide** hides them. **Show all** brings everything back. A counter shows how many are hidden.',
        'Hiding and isolating only change your own view. Nothing is deleted.',
    ]),
    H3('Elements panel'),
    P('One tick box per category (Walls, Floors and slabs, Columns, Windows, Doors, Furniture, Railings...) with a count. Untick a category to hide it; **Show all** turns them all back on. Your choice is remembered.'),
    H3('Model browser'),
    UL([
        'A tree of **model › category › family / type › elements**. Click a row to open it and pick that group; click an element to highlight and zoom to it.',
        '**Search names, types, levels, properties**: plain words match name, category, family, type and level. Use **property:value** to match a parameter, for example Fire Rating:2 hr or Mark:D101.',
        '**Select** colours what you found, **Isolate** shows only that, **Zoom** frames it. After **Select**, **+ Task** at the top keeps all the selected elements on a task as "Elements to change", and **Copy Revit ID** copies all their ids.',
        'The browser works with models published in the fast 3D format (the normal Publish to Viewer output).',
    ]),
    H3('Display'),
    TABLE(['Mode', 'Use it for'], [
        ['**Shaded**', "Normal viewing with the model's own colours"],
        ['**White**', 'A clean, colour-free look for reviews and screenshots'],
        ['**X-ray**', 'See through walls and floors to what is inside'],
    ]),
    P('The **Display** panel also sets the background colour, the ground (on/off and colour) and the grid.'),
    H3('Saved views'),
    UL([
        '**Save** (or right-click **Save view...**) stores the camera, section and hidden elements with a name and a thumbnail. Saved views are shared with the whole project.',
        'Click a saved view to return to it; **✕** deletes it.',
        'When you go from 3D to Sheets and back, your last 3D view comes back as you left it.',
    ]),
    H2('Section box, section plane and floor plans'),
    P('Use the section box to cut a part of the building open, and a section plane to cut along any surface; cut solids show an orange hatch, as on a drawing.'),
    H3('Section tools'),
    TABLE(['Button', 'What it does'], [
        ['**Box** (tick)', 'Turns the section box on, fitted round the whole project'],
        ['**Plane**', 'Click a surface: the model is cut on that face'],
        ['**Align**', 'Click a wall: the box turns square to that wall'],
        ['**Flip**', 'Keeps the other side of the section plane'],
        ['**Reset**', 'Removes all cuts'],
        ['**Solid fill on the cut**', 'Cut walls, slabs and columns show an orange hatch (on by default)'],
        ['**Plan look for floor plans**', 'In a floor plan, surfaces are paler and floors below fade out (on by default)'],
    ]),
    P('The Floor plan drop-down (see 3D: moving around) is a ready-made section box for one storey.'),
    H3('Moving a cut'),
    UL([
        'Each face of the box has a **coloured dot on a short stem**: red for X, green for Y, blue for height. The single section plane has an orange dot.',
        '**Mouse:** hover over a dot, or over the edge of a cut face (the face lights up orange), then drag. The cut only moves along its own direction.',
        '**iPad / iPhone:** drag a dot with one finger. Two fingers always move the view, never the cut, so you can pinch and orbit freely while a section is on.',
        'On a computer, a brown outline traces the cut edges once the cut stops moving. Phones and tablets show the hatch only.',
    ]),
    H3('Handy shortcuts'),
    UL([
        'Right-click a wall or floor: **Section on this face** cuts right there; **Square section box to this face** lines the box up with it.',
        'Right-click empty space: **Turn section on/off**.',
    ]),
    H2('Measuring in 3D'),
    P('Every measured point snaps to a real corner, edge or midpoint, and the label tells you which, so you know whether to trust the figure.'),
    H3('How to measure'),
    OL([
        'Click **Measure** in the top bar (or right-click **Measure**) and choose **Distance**, **Angle** or **Area**.',
        'Move the pointer over the model. A coloured dot and label show the snap under it.',
        'Click the first point, then the next. The distance updates live as you move, with its **plan** and **height** parts.',
        'Press **Esc** to drop a measurement you started by mistake.',
    ]),
    TABLE(['Mode', 'Points', 'Result'], [
        ['**Distance**', '2', 'Length (mm under 1 m, otherwise m), plus plan and height parts'],
        ['**Angle**', '3', 'Degrees at the middle point'],
        ['**Area**', '3 to 64', 'Area in m² of the polygon'],
    ]),
    H3('Snaps'),
    TABLE(['Colour', 'Snap', 'Meaning'], [
        ['Red', 'corner', 'A vertex of the element, or a corner of the cut in a section'],
        ['Purple', 'midpoint', 'The middle of an edge'],
        ['Green', 'perpendicular', 'The foot of a square line from your last point to an edge'],
        ['Blue', 'edge', 'Anywhere along an edge'],
        ['Grey', 'surface', 'No feature nearby: the point on the face (less exact)'],
    ]),
    UL([
        'A ring runs out from each new snap (and the phone vibrates) so you know it caught.',
        'In a floor plan or section, the snaps follow the cut outline, so you can measure wall to wall in plan.',
        'Curved surfaces are made of small flat faces, so there is no tangent or centre-of-arc snap yet.',
    ]),
    H3('Straight and other buttons'),
    UL([
        '**Straight** keeps the next point in line with the last one along X, Y or height, for true orthogonal distances. Hold **Shift** to switch it for one point.',
        '**Undo** removes the last point, **Clear** removes all measurements.',
        '**Keep** saves a finished distance as a dimension that everyone on the project sees. The **Dimensions** tick box shows or hides kept dimensions, and each one can be removed with **✕**.',
    ]),
    H2('Walking through the model'),
    P('Walk mode puts you at eye level inside the building, following floors, stairs and ramps.'),
    P('**Start:** click **Walk**, then click a floor (clicking a wall places you on the floor in front of it). Or right-click a spot and choose **Walk from here**. Walking turns off the floor plan and section box.'),
    TABLE(['Action', 'Keyboard / mouse', 'iPad / iPhone'], [
        ['Forward / back', 'W / S or ↑ / ↓', 'On-screen pad'],
        ['Step sideways', 'A / D', 'On-screen pad'],
        ['Turn', '← / →, or drag with the mouse', 'Drag with a finger, or the pad'],
        ['Look up and down', 'Drag with the mouse', 'Drag with a finger'],
        ['Faster', 'Hold Shift (3× speed)', '-'],
        ['Step forward or back', 'Scroll wheel', '-'],
        ['Floor above / below', 'Page Up / Page Down', '-'],
        ['Up / down (Gravity off)', 'E / Q', '-'],
        ['Stop walking', 'Esc or **Stop**', '**Stop**'],
    ]),
    P('**Walking panel settings** (remembered):'),
    UL([
        '**Eye** height, 0.8 to 3 m (default 1.6 m).',
        '**Speed**, 0.5 to 8 m/s (default 1.5 m/s).',
        '**Gravity** (on): stay on the floor, climb stairs and ramps, ignore desk-height steps.',
        '**Walls block** (off): stops you walking through walls. Doors are closed in the model, so doorways block too when this is on.',
    ]),
    P('On the Sheets page, **2D + 3D** with **Walk** lets you walk in 3D while the plan beside it shows where you are.'),
    H2('Consultant models (IFC)'),
    P('Models from other companies (structure, MEP, interior, facade) can be shown with the project\'s own. Ask them for **IFC** (IFC 2x3 or IFC4): SketchUp, Revit, Tekla, ArchiCAD and Rhino all export it, and it keeps the elements, their properties and their real coordinates. ("WebGL" is how a browser draws; it is not a file to exchange.)'),
    TABLE(['Use', 'How'], [
        ['Add to this project\'s 3D', '**Models** panel > **+ Consultant model (IFC)**: choose the .ifc, give its name, company and discipline, **Upload and convert**. The server converts it (a bar shows the progress); it then appears under **Consultant models**'],
        ['Overlay another project\'s model', '**+ Overlay another project**: pick a project you can open and one of its models. It is shown here on the shared coordinates both use'],
        ['A 3D page of its own', 'An admin makes it with **New 3D project from IFC** (Admin). For a model whose coordinates match nothing: a standalone reference, which can still be overlaid later'],
    ]),
    UL([
        'Each consultant model has a tick box (on / off for you) and a slider to make it see-through.',
        '**Place** (the person who added it, or a project admin) sets where it sits for everyone: **Shared coordinates** (what a coordinated consultant exports), **This model\'s origin**, or **No coordinates: set in the middle**; then **East / North / Up** (mm) and **Turn** (°) move it by hand while you watch. **Save for everyone** keeps it; **Cancel** puts it back.',
        'Its elements can be clicked and issues raised on them like the project\'s own.',
        '**×** removes it from the project (who added it, or a project admin).',
    ]),
    H2('Issues and BCF'),
    P('An issue is a markup or a 3D point with a title, type, owner, due date and a conversation; it is numbered by the server (#N) and the same issue appears on Sheets, in 3D, on the Dashboard and in Revit.'),
    H3('Raising an issue'),
    TABLE(['Where', 'How'], [
        ['On a sheet', 'Switch the top bar to **Issue** and draw a markup; or select a markup and press **Issue**; or right-click it and choose **Raise issue**. A sharp picture of the drawing is attached automatically: it is drawn from the PDF itself at about 200 dpi, whatever the zoom or the speed settings of your computer.'],
        ['In 3D', 'Click **Add issue**, then click the spot (on iPad: long press). The camera, section and hidden elements are saved with it, and a snapshot is attached. **Mark up snapshot** lets you draw on the picture (clouds, arrows, text and more).'],
    ]),
    P('Fill in the issue window, then **Save issue**:'),
    TABLE(['Field', 'Notes'], [
        ['**Title**', 'Required, up to 120 characters. Say what is wrong and where, for example "L12 corridor: fire door swing clashes with riser"'],
        ['**Type**', 'General, Design, Coordination, Clash, Fire safety, Statutory / BD, Structure, MEP, Facade, Drawing error, Query / RFI'],
        ['**Description**', 'What is wrong, what you expect, any reference'],
        ['**Assign to**', 'Pick a project member (or type a name)'],
        ['**Due**', 'The date an answer is needed'],
        ['**Status**', 'Open, In progress, Resolved, Closed'],
        ['**Priority**', 'Low, Normal (default), High, Critical'],
        ['**Template**', 'Load a saved set of fields; **Save as template** shares the current one with the project'],
    ]),
    H3('Working an issue'),
    UL([
        'Click an issue in the list (or its pin in 3D) to open it. In 3D the view goes back to exactly what the author saw: the same eye and direction, the section box with its turn (or the section plane), hidden elements, parallel or perspective view and the floor plan. **Show in view** and links to the issue do the same.',
        '**In Revit** (LWK Issues > **Go to**): an issue seen through the viewer\'s normal camera, or raised while walking, opens in a perspective camera view **LWK Issue - <you> (camera)** from the same eye, with the same section box, not a view of the whole building from outside.',
        'In the issue window: edit the title and fields, **Add photo** (site photos, several at once), and write in **Add a comment** then press **Comment**. Type **@** to mention a project member.',
        '**Show in view** returns to the spot; **Show in 3D** opens the 3D page there.',
        '**Not an issue** closes it with a reason that everyone can read; the same button reopens it.',
        '**Delete** removes it for everyone. Members can delete only their own issues; project admins can delete any.',
        '**Revit element** (3D issues): the element it was raised on, with **Copy Revit IDs**, **Show in 3D** and **Show in Revit**.',
        '**Tasks:** the tasks that point at this issue, with their owner and due date. **+ New task from this issue** makes one (see Issues and tasks together); **Send to chat** posts the issue into a chat.',
        'Setting the status to **Resolved** or **Closed** and pressing **Save**: if tasks on the issue are still open, the viewer offers to mark them done.',
    ]),
    H3('Status: who does what (team practice)'),
    TABLE(['Status', 'Set by', 'Meaning'], [
        ['Open', 'Author', 'Raised, waiting for the assignee'],
        ['In progress', 'Assignee', 'Being worked on'],
        ['Resolved', 'Assignee', 'Fixed or answered; waiting for the author to check'],
        ['Closed', 'Author or project admin', 'Checked and done'],
    ]),
    H3('Finding issues'),
    UL([
        '**Sheets:** the right panel lists **All / Issues / Comments**, grouped by Sheet, Status, Assigned to, Raised by, View, Issue type or Markup type, with a **Search** box. Right-click an entry to open it, show it on the sheet or in 3D, or change its status.',
        '**3D:** **Issues in 3D** groups by Status, Floor, Issue type, Assigned to, Raised by or Model. **Sheet issues** also shows issues raised on sheets as diamonds in the model. **Hide issues** hides the pins (nothing is deleted).',
        '**Dashboard:** filters, overdue lists and the responsibility table (see Dashboard and projects).',
    ]),
    H3('BCF: issues with Revit, Navisworks and others'),
    UL([
        "**Export BCF** (3D page) and **BCF** (Sheets page) download a BCF 2.1 file with each issue's title, status, priority, dates, author, assignee, description, camera, selected element and snapshot. Plain comments without an issue are left out, as are the issue type, the comment thread and added photos.",
        "The selected element is written with its IFC GUID **and its Revit ElementId** (AuthoringToolId), so Revit BCF tools such as Autodesk BCF Manager, BCFier and Revizto select it in Revit.",
        '**Import BCF** (3D page only) reads BCF 2.0, 2.1 and 3.0 from Revit, Navisworks, Solibri or ACC. It first asks which coordinates the file uses: choose **Work it out (recommended)** unless you know. Issues already imported (same ID) are skipped.',
    ]),
    H2('Issues and tasks together'),
    P('An issue says what is wrong; a task says who fixes it by when. The two are linked and each offers to close the other.'),
    UL([
        '**A task from an issue:** in the issue window press **+ New task from this issue**. The task list and group of this project come first, the owner is the issue\'s **Assigned to**, and the due date is the issue\'s. The issue, its files and its Revit element go on the task. Tick **Open the task when made** to go to it.',
        '**Task done → issue:** when you **Mark complete** a task whose linked issues are still open, Tasks asks **Resolve its issues too?** Tick the ones to change and choose Resolved or Closed. They are changed as if you did it in the viewer: history, emails, the chat card, and a comment naming the task.',
        '**Issue resolved → task:** set an issue to Resolved or Closed and **Save**; if its tasks are still open, the viewer offers to mark them done. The tasks also get a line in their activity.',
        'The task window shows each linked issue\'s status now; the task list shows **#n open** or **#✓**.',
    ]),
    H2('Revit elements'),
    P('A 3D issue keeps the Revit element it was raised on: **ElementId**, **UniqueId**, IFC GUID, category, family / type and level. Models published by the LWK add-in know all of these; older ones only the IFC GUID.'),
    TABLE(['To', 'Do this'], [
        ['Select it in Revit now', '**Copy Revit ID** (or **Copy Revit IDs**), then in Revit **Manage > Select by ID** and paste. Works today, no add-in change needed'],
        ['See it in 3D', '**Show in 3D**: the 3D page picks the element(s) out and zooms to them'],
        ['Have Revit select it', '**Show in Revit** asks the LWK add-in to select it in Revit. Until the add-in supports this, the ids are copied for Select by ID instead'],
        ['Hand it to a colleague', 'Select elements on the 3D page and press **+ Task**: they go on the task as **Elements to change**, with the same buttons'],
        ['Send it to another tool', '**Export BCF**: Revit BCF tools select the element from its ElementId'],
    ]),
    H2('Search'),
    P('One box for everything: press **Ctrl+K** or **/** on any page, or click the magnifier at the top.'),
    UL([
        'It finds **projects**, **tasks** (title, description, T-12), **issues** (#12, title, description, sheet, assignee, Revit element and id), **sheets**, saved **3D views**, **messages**, and **files and links** on tasks and issues.',
        'Type one or more words; every word must match. Results are grouped by kind; ↑ ↓ and **Enter** open one, **Esc** closes.',
        'You only see what you may open. Your last searches are listed when the box is empty.',
    ]),
    H2('Working offline'),
    P('On site with no signal, a project downloaded to the device keeps working: sheets, the 3D model, issues and markups.'),
    OL([
        'With a connection, open the project and press **Offline** in the top bar, then **Download for offline**. The download shows its progress and can be continued if it stops.',
        'Without a connection the top bar says **Offline - copy of <date>**. Look at sheets and the model, raise and answer issues, draw markups.',
        'Changes made offline wait on the device (**N changes waiting**) and upload by themselves when the connection is back (**All changes uploaded**).',
    ]),
    UL([
        'The Dashboard, Admin, Board, Tasks, Messenger, comparing with earlier versions and adding PDFs need a connection.',
        'On iPad and iPhone, **Add to Home Screen** first: Safari may clear a website it has not seen for some weeks, but keeps the Home Screen app.',
    ]),
    H2('Phones and tablets'),
    P("The same address works on iPad and iPhone in Safari; the viewer detects the device and loads a lighter 3D model so it fits in the device's memory."),
    LABEL('What is different on a phone or tablet'),
    UL([
        'The side panels become drawers: **☰ Models** / **☰ Sheets** on the left and **ⓘ Details** / **Issues** on the right. Tap outside a drawer to close it. A dot on Details means something was picked.',
        '3D loads a phone copy of each model, made on the server after every publish. On big projects, geometry is fetched in pieces as you look around ("streaming"), coarse first, then finer.',
        '**Light mode** is on: repeated typical floors load only near where you are looking.',
        'Small items such as furniture are drawn only near the camera, and far parts use simpler shapes.',
        'Cut solids show the orange hatch but no brown outline.',
        'The top bar scrolls sideways: swipe it to reach Board, Tasks, Chat and Dashboard.',
        '**Search** fills the screen. In **Messenger**, tap a message to show its buttons; Enter makes a new line and the round button sends.',
    ]),
    LABEL('Gestures'),
    TABLE(['Gesture', '3D', 'Sheets'], [
        ['One finger', 'Orbit', 'Draw with the current tool (pans after you have used an Apple Pencil)'],
        ['Two fingers', 'Pinch to zoom, drag to pan', 'Pinch to zoom, drag to pan'],
        ['Double tap', 'Focus on that surface', '-'],
        ['Long press', 'New issue at that point', 'Right-click menu'],
        ['Two-finger / three-finger tap', '-', 'Undo / redo'],
    ]),
    LABEL('Tips'),
    UL([
        'Use landscape on iPad for the most drawing space.',
        'If a model was published minutes ago, its phone copy may still be being prepared; the page offers to prepare it and you can try again a few minutes later.',
        'If Safari reloads the page by itself, the device ran out of memory: untick models you do not need in **Models**, stay on one floor, and send a report (see Troubleshooting).',
    ]),
    H2('Performance panel and settings'),
    P('The **Performance** link at the bottom right of the 3D page opens load times, frame rate and memory, plus a few settings; **Copy** puts the whole report on the clipboard to paste into an email or Teams message when you report a problem.'),
    TABLE(['Setting', 'Choices', 'What it does'], [
        ['**Streaming**', 'automatic / on / off', 'Fetch big models in pieces as the view needs them (automatic = on for phones and tablets)'],
        ['**Memory budget**', 'automatic / 150 to 1500 MB', 'How much geometry the device keeps before letting go of what is out of sight'],
        ['**Drawing with**', 'WebGL (standard) / WebGPU (trial)', 'The graphics method; the page reloads to switch. Keep WebGL unless asked to test'],
        ['**While moving**', 'follow the frame rate / always full quality', 'When the frame rate drops while you move, draw a lighter moving picture; the still view is always full quality'],
    ]),
    P('Streaming and memory budget apply after reloading the page. The status bar also shows the live frame rate, triangles drawn and graphics memory; "moving step 1 to 4" means the lighter moving picture is in use.'),
    LABEL('Loading speed'),
    UL([
        'The viewer\'s files are sent compressed (the 3D library drops from 4.8 MB to 0.7 MB) and are kept by your browser: from the second visit on, a page opens from your own computer and only its data comes from the server.',
        'Each page asks for all its data at once while it loads. The Messenger and the Projects page also show what they showed last time straight away, then update.',
        'After an update of the viewer, changed files are fetched again by themselves; you never get a mix of old and new.',
    ]),
    H2('For BIM coordinators: publishing from Revit'),
    P('One button, **Publish to Viewer**, exports the sheets and the 3D model and uploads them; the other buttons are for doing the same steps by hand or overnight.'),
    H3('Setup (once per computer)'),
    UL([
        'Install the LWK pyRevit extension. It adds an **LWK** tab with the **Viewer & Issues** panel: **Publish to Viewer**, **LWK Issues** and the **Viewer tools** pulldown.',
        'Sign in once (in **LWK Issues** or from **Publish**). The sign-in is kept for a year so nightly uploads keep working.',
        'To upload to an existing project you must be its **project admin**; a new project name needs a **site admin**.',
    ]),
    H3('Publish to Viewer'),
    OL([
        'Open the model in Revit and click **Publish to Viewer**.',
        '**Where:** pick the **Viewer project** (or type a new name: letters, digits, - and _), check the **Server** shows "signed in", and the **Export folder**.',
        '**What:** tick **3D model (fast format, with its linked models)** and choose the detail: **Coarse (lightest)**, **Medium (recommended)** or **Fine (most detail)**. Tick **Sheets** and choose **All sheets**, **A Revit sheet set**, or **These sheets**. **Keep sheets published before** keeps earlier sheets that are not in this choice.',
        '**Then:** **Send to the viewer server (only what changed)**, **Open it in the browser when done**, and optionally **Publish this model again every night at** 01:00 (Mon-Fri only if you like; ACC models only).',
        'Press **Publish**. Choices are remembered for this model. The Revit model is not changed or saved.',
    ]),
    P('After the upload the server needs a few minutes to prepare phone copies and read the sheet text. The server keeps the last 12 versions of each sheet PDF (for **Compare**) and the last 2 of each 3D model (for **Compare with previous export**).'),
    H3('Viewer tools pulldown'),
    TABLE(['Button', 'Use it to'], [
        ['**Fast 3D Export**', 'Export only the 3D model (and links) in the fast format; sheets are kept'],
        ['**Export Viewer**', 'Export sheets and the manifest by hand (older IFC route)'],
        ['**Upload Now**', 'Send the last export to the server again'],
        ['**Add Model**', 'Register an ACC model for the automatic export: sheets, IFC schema, categories to leave out, typical-floor groups'],
        ['**Run Export**', 'Export and upload every registered model now (Shift-click: only the open model)'],
        ['**Night Export**', 'Schedule every night or weeknights, remove the schedule, or see status and logs'],
        ['**Export Link**', 'Export a link that the automatic export cannot open (for example an older-version cloud model)'],
        ['**Link Places**', "Write every link instance's placement to the export folder"],
        ['**Test Links**', 'Quick check of links placed more than once'],
    ]),
    P('**Nightly export needs:** the PC left on and logged in (a locked screen is fine), Revit closed at the scheduled time, and Revit signed in to Autodesk. Allow about 15 minutes per model. Logs are in %APPDATA%\\LWK\\nightly.'),
    UL([
        'Every workset of the model is opened by name and unloaded links are loaded. If a workset is still closed, or the 3D model comes out empty, the viewer **keeps the last good 3D model** (the sheets still go), and the log ends with **result FAILED** and the reason.',
        'Known dialogs are answered so the night is not stopped: a DWG with an empty paper space (Yes), DWG import notes (Close), and **External Tools - Add-in Assembly Not Found** at start-up (Close, by the launcher\'s watcher). Every dialog is written to nightly\\dialogs.log. Best: repair or remove the broken add-in on that PC.',
    ]),
    H3('LWK Issues window in Revit'),
    UL([
        "Lists the viewer's issues for a project: **Show** open and in progress, assigned to me, or all; search; columns #, Title, Type, Status, Priority, Assigned to, Due, Where.",
        '**Go to issue** (or double-click) opens a personal 3D view "LWK Issue - your name" with a section box round the issue, or zooms the sheet. **Open its plan view** and **Open in web viewer** are beside it.',
        '**Place pins for the list** / **Remove pins** add "LWK #n" markers on the workset "LWK Issues". **Clouds on sheets** adds revision clouds under the revision "LWK Viewer issues".',
        'Choose a status and/or type a comment, then **Send to viewer**: it appears in the web viewer under your name.',
    ]),
    H3('Revit elements and the LWK add-in'),
    UL([
        'Every issue raised in 3D on a published model carries the element\'s ElementId and UniqueId. Reviewers can copy the ids for **Manage > Select by ID**, and BCF exports carry them as AuthoringToolId.',
        '**Show in Revit** in the viewer leaves a request on the server for the add-in to pick up; the add-in can also send what is selected in Revit to the viewer. What the add-in needs to do is written in **server/REVIT_ADDIN_API.md**, for whoever maintains it.',
    ]),
    H2('For admins'),
    P("Project admins manage their project's people and settings on the **Admin** page; site admins also manage accounts, every project, the bin and device reports."),
    H3('Roles'),
    TABLE(['Role', 'Can'], [
        ['**Viewer**', 'Look at everything; cannot add or change issues or comments'],
        ['**Member**', 'Raise and edit issues and comments; delete only their own'],
        ['**Project admin**', "Everything a member can, plus manage the project's members, edit or delete anything, override layer locks, upload models"],
        ['**Site admin**', 'Every project; add, deactivate and reset accounts; create, delete and restore projects'],
    ]),
    P('Every project must keep at least one project admin.'),
    H3('Projects and members'),
    UL([
        '**Add people to this project:** search, narrow by **team**, **office** or **company**, tick several (or **Select all shown**), choose the Role and press **Add N people**; or fill in **Someone without an account yet** (Email, Name, Office, Company, Role) and **Create and add**. A temporary password is shown **once**.',
        'Send it with **Email invitation** (opens your own Outlook) or **Copy invitation**. The person must choose their own password at first sign-in.',
        'Change a role in the members table, or **Remove** someone (their issues and comments stay).',
        '**Teams channel:** paste the Teams Workflow webhook address, **Save**, **Send a test**, and choose the day and hour (Hong Kong time) for the weekly summary.',
        '**Markup layers:** for each layer set who can change it (every member, project admins only, or named people), who can see it, and whether it starts hidden.',
        "**Phones and tablets:** **Prepare this project now** re-makes the phone copies if a phone reports none; **Show progress** (site admins) shows the server's background work.",
    ]),
    H3('Projects (Admin > Projects and members)'),
    UL([
        '**+ New project**: **Project name** (e.g. HKA-P-01681-ARC - SKW; the code is taken from it), **Code**, **Status**, **Group / team**, **Owners**, and **Folders and files** (OneDrive, SharePoint or ACC links). **Import** reads a project table exported from Lark Base or Excel.',
        '**Models and sheets:** the viewer projects (export folders) that show this job. Ctrl+click several when a job has several Revit models and sheet sets, such as Site 1 and Site 2. Choosing one already used elsewhere moves it here; an entry the server made for it alone is removed, and its task groups move with it.',
        'Members belong to each part (they are what lets someone open that model). With several parts, a **Part** selector appears above the members table.',
        '**Remove from Projects** takes a job off the Projects page; its tasks, issues, model and files stay.',
    ]),
    H3('Site admin only'),
    UL([
        '**People:** add accounts, **Reset password**, **Make / Remove site admin**, **Deactivate / Reactivate** (signs the person out everywhere), **Edit**, **Delete** (for accounts made by mistake).',
        '**Delete project ...:** type the project name to confirm. Models, sheets, issues, markups and members move to the bin on the server; **Restore** in the bin list puts everything back, as long as the name has not been reused.',
        '**Devices:** reports sent by the 3D page from each device: what loaded, peak memory, frame rate, stalls and crashes. Filter to crashes or to phones and tablets to see where the viewer struggles.',
        '**Server:** email needs the server\'s LWK_SMTP_ settings. If a proxy in front of the server has trouble with the compressed, browser-kept files, start the server with --plain-assets (or set PLAIN_ASSETS=1 in run.bat).',
    ]),
    H2('Troubleshooting and FAQ'),
    P('Most problems are an old cached page, a slow connection or a device short of memory; the table gives the first thing to try.'),
    TABLE(['Problem', 'Try this'], [
        ['Something looks old or a new feature is missing', 'Check the version next to "LWK Viewer" at top left; press Ctrl+F5 (Windows) or Cmd+Shift+R (Mac). On iPad, close the tab and open it again'],
        ['"Wrong email or password"', 'Check the email; ask an admin to **Reset password**. After 10 tries, wait 15 minutes'],
        ['"You are not a member of this project"', 'Ask the project admin to add you'],
        ['I cannot add or change issues', 'You are a **Viewer** on this project; ask the project admin for Member'],
        ['"N waiting to save"', 'Your connection dropped. Keep the page open; it saves when the connection returns'],
        ['The newest sheets or model are not there', 'The publish may still be running, or the server is preparing it; wait a few minutes and reload'],
        ['3D is slow or jerky on a computer', 'Untick models you do not need, use a floor plan, check **While moving** is on "follow the frame rate"'],
        ['iPad or iPhone reloads the page by itself', 'It ran out of memory: open fewer models, stay on one floor, keep **Light mode** on; send the Performance report'],
        ['An element cannot be clicked in a section', 'Only the visible side of the cut can be picked; move the cut or use the Model browser'],
        ['The measure snaps to the wrong thing', 'Zoom in closer; hold still until the label shows **corner**, **midpoint** or **edge**'],
        ['A Revit link is missing or misplaced', 'Check **Apply link transforms** is on; tell the BIM coordinator'],
        ['Pages look different after switching to WebGPU', 'In Performance, press **Drawing with** to go back to WebGL (or add &gpu=webgl to the address once)'],
        ['A page is slow to open over a VPN or from home', 'The second visit is much quicker (the files stay in your browser). If first visits stay slow, ask IT to turn on HTTP/2 on the server\'s proxy'],
        ['Search finds nothing', 'Type at least 2 letters; every word must match. You only see projects, lists and chats you are a member of'],
        ['"Revit\'s LWK add-in is not listening"', 'The ids were copied instead: in Revit use **Manage > Select by ID** and paste'],
        ['WhatsApp import: "does not look like a WhatsApp chat export"', 'Use WhatsApp\'s **Export chat** file (.txt or .zip), not a screenshot or a forwarded message'],
        ['A task or message link opens nothing', 'You may not be a member of that list, chat or project; ask its owner'],
        ['There is no Delete for a message or a chat', 'Only the sender deletes a message. A group is deleted by its admins, a project channel or topic by the project\'s admins'],
    ]),
    P('**When you report a problem,** send: the project, the page (Sheets or 3D), your device and browser, what you did, a screenshot, and on the 3D page the **Performance → Copy** report.'),
    LABEL('FAQ'),
    UL([
        '**Does it change the Revit model?** No. Publishing only reads the model. Only the LWK Issues window adds pins or clouds, and only when you ask.',
        '**Who can see my markups?** Everyone on the project, unless the markup is on a layer an admin has restricted.',
        "**Does it send email?** Yes, when the server's mail is set up: task assignments, @mentions, comments and completions on tasks you follow, and a daily list of tasks due. Teams posts as before.",
        '**Can I use it offline?** Yes, for a project downloaded to the device (see Working offline). Short drops are fine anyway: changes wait and save when the connection returns.',
        '**Does the Messenger replace WhatsApp?** It is for project work, next to the drawings and tasks. Messages can be sent to WhatsApp and brought in from it, but the two are not linked automatically.',
        '**Can consultants use it?** Yes, with their own account, usually as **Viewer** or **Member** on that project only.',
    ]),
    H2('Shortcuts cheat sheet'),
    P('Print this table or keep it beside the screen for the first week.'),
    TABLE(['Where', 'Key or button', 'Action'], [
        ['3D', 'Right button drag', 'Orbit'],
        ['3D', 'Middle button drag', 'Pan'],
        ['3D', 'Wheel', 'Zoom towards the pointer'],
        ['3D', 'Double-click', 'Focus on that surface'],
        ['3D', 'Right-click (no drag)', 'Menu, and move the orbit centre there'],
        ['3D', 'Page Up / Page Down', 'Floor above / below'],
        ['3D', 'Esc', 'Cancel a measurement, stop walking, close a menu'],
        ['3D measure', 'Shift', 'Straight on or off for one point'],
        ['3D walk', 'W A S D, ↑ ↓', 'Move and step sideways'],
        ['3D walk', '← →', 'Turn'],
        ['3D walk', 'Shift / Q / E', 'Faster / down / up (Gravity off)'],
        ['Sheets', 'Wheel / middle drag', 'Zoom / pan'],
        ['Sheets', 'Page Down / Page Up', 'Next / previous sheet'],
        ['Sheets', 'V / H', 'Select tool / Pan tool'],
        ['Sheets', 'Enter, Esc, Backspace', 'Finish, end, or remove the last point of a polyline'],
        ['Sheets', 'Delete', 'Delete the selected markup'],
        ['Sheets', 'Ctrl+A', 'Select all markups on the sheet'],
        ['Sheets', 'Ctrl+C / Ctrl+V', 'Copy / paste markups (also to another sheet)'],
        ['Sheets', 'Ctrl+Z / Ctrl+Y', 'Undo / redo'],
        ['Sheets', 'R / Shift+R', 'Rotate the selection 90° clockwise / anticlockwise'],
        ['Sheets compare', 'N / Shift+N', 'Next / previous change'],
        ['Every page', 'Ctrl+K or /', 'Search everything'],
        ['Search', '↑ ↓, Enter, Esc', 'Move, open, close'],
        ['Tasks', 'K / J', 'Previous / next task'],
        ['Messenger', 'Enter / Ctrl+Enter', 'New line / send'],
        ['Messenger', '@ # ! $ %', 'Mention a person / link a task, issue, sheet, 3D view'],
        ['Messenger', 'Ctrl+Enter / Esc (editing)', 'Save / cancel an edited message'],
        ['Messenger', 'Ctrl+B / Ctrl+I / Ctrl+Shift+X', 'Bold / italic / strikethrough'],
    ]),
    H2('Feedback and what to try first'),
    P('This is a trial: please try the tasks below and tell us what works, what is confusing and what is missing.'),
    UL([
        '☐ Sign in and change your password',
        '☐ Find a sheet by searching for a room name or note',
        '☐ Mark up a sheet with a cloud and text, then turn it into an issue',
        '☐ Open the same area in 3D and cut a floor plan',
        '☐ Measure a room wall to wall in plan, with **Straight** on',
        '☐ Raise an issue in 3D, assign it to a colleague, and comment with an @mention',
        '☐ Try **2D + 3D** and walk a corridor while watching the plan',
        '☐ Open the viewer on an iPad or iPhone and look at one floor',
        '☐ Make a task from your test issue, then complete it and resolve the issue from the Tasks page',
        '☐ Send a message in your project\'s channel with a # task and a $ sheet link',
        '☐ Open a topic in your project channel, pin a message, and send a poll and an event',
        '☐ Find your test issue with Ctrl+K',
        '☐ In 3D, click an element, press Copy Revit ID and select it in Revit with Select by ID',
        '☐ Delete your test issues and tasks when you finish',
    ]),
    P('Send feedback, questions and problem reports to [name / Teams channel]. Include the Performance report for anything to do with speed or crashes.'),
]
