# 廣東話版 第一部分：開頭至「Dashboard 同 project」

from blocks import *

PART = [
    BLANK(),
    H1('LWK Viewer 使用手冊'),
    P('2026 年 10 月 4 日 · @Wilson · 適用於 viewer 版本 2026-10-08'),
    H2('LWK Viewer 係乜嘢'),
    P('LWK Viewer 喺網頁瀏覽器入面顯示 project 嘅 Revit sheet 同 3D model，所以團隊入面任何人唔使開 Revit 都可以睇圖、度尺、畫 markup 同開 issue。電腦、iPad 同 iPhone 都用得，每個開咗嘅 issue 會即時同晒成個團隊分享，仲可以喺 Revit 入面跟返。'),
    P('除咗圖則同 model，佢仲放埋團隊嘅工作：project 清單、task list（取代 Lark Tasks）、白板同 Messenger，全部都連住同一批 sheet、3D 視圖同 issue，仲有一個搜尋可以一次過搵晒所有嘢。'),
    LABEL('邊個會用'),
    TABLE(['邊個', '通常用嚟'], [
        ['建築師同設計師', '睇圖同 3D model，開設計同協調 issue，回覆指派俾自己嘅 issue'],
        ['Project lead 同 director', '用平板睇進度，喺 Dashboard 跟進未完成同過咗期嘅 issue'],
        ['BIM coordinator', '由 Revit publish model 同 sheet，行晚間 export，喺 Revit 入面處理 issue'],
        ['顧問同地盤同事（Viewer 角色）', '任何裝置都只係睇同讀'],
        ['Team lead', '安排團隊嘅 task list，跟進邊個幾時要做乜，喺 project channel 傾'],
        ['Project admin 同 site admin', '加人、set 角色、管理 project'],
    ]),
    LABEL('可以做乜'),
    UL([
        '**Sheets (2D)：** 打開每張 publish 咗嘅 sheet，係清晰嘅 PDF；搜尋所有圖則上面嘅字；用 20 幾款工具畫 markup；同舊版本比較；連 markup 一齊 export PDF。',
        '**3D：** 轉、移、喺 model 同佢嘅 link 入面行；切平面圖同剖面；有 snap 咁度尺；睇元件 property；儲存視圖。',
        '**Issue：** 喺 sheet 或者 3D 開 issue，會連一張截圖；指派俾人、set 限期、用 @mention 留言，一路跟到關為止。Issue 可以透過 BCF 同 Revit、Navisworks、BIMcollab 互通。',
        '**2D + 3D 並排：** 喺 sheet 上面撳平面圖，3D 就會去返嗰度；喺 3D 行嘅時候，平面圖會顯示你喺邊。',
        '**Revit 連接：** Revit 入面嘅 LWK Issues 視窗會列出同一批 issue，可以 zoom 去嗰度，亦可以傳回覆返嚟。',
        '**Projects：** 每個 job 嘅人、圖則、model、task、issue、檔案同 chat 都喺同一版。',
        '**Tasks：** 團隊 task list，有 List、Kanban、Gantt 同 Dashboard 幾種睇法，可以由 Lark import，亦連住 issue、sheet 同 3D 視圖。',
        '**Board：** 每個 project 一塊共用白板，可以寫 note、整 mind map 同畫草圖。',
        '**Messenger：** project channel、group chat 同私訊；task 同 issue 嘅更新會自動貼入嚟；可以連去 task、issue、sheet 同 3D；仲可以同 WhatsApp 互傳訊息。',
        '**Issue 同 Task 打通：** 由 issue 直接開 task；完成其中一樣，會問你要唔要一齊關埋另一樣。',
        '**Revit 元件：** 3D issue 會記住 Revit ElementId，用嚟做 Select by ID、BCF 同 LWK add-in。',
        '**搜尋：** 一個搜尋框（Ctrl+K）搵晒 task、issue、sheet、3D 視圖、訊息同檔案連結。',
        '**Offline：** 將 project 下載落平板，喺地盤冇訊號都照用得。',
    ]),
    H2('開始之前'),
    P('你需要一個 account、一個支援嘅瀏覽器同 viewer 嘅網址；電腦唔使裝任何嘢。'),
    LABEL('你嘅 account'),
    UL([
        'Admin 會幫你開 account，再寄邀請俾你，入面有一個**臨時密碼**。',
        '打開 viewer 網址，用你嘅 **Email** 同臨時密碼登入，跟住喺彈出嚟嘅 **My account** 版揀返自己嘅密碼（最少 8 個字）。',
        '每個瀏覽器會保持登入 30 日。15 分鐘內打錯 10 次密碼，登入會停 15 分鐘。',
        '角色係逐個 project 設定：**Project admin**、**Member** 或者 **Viewer**（睇「俾 admin 嘅」）。Viewer 會見到一條橫額，話佢只可以睇同讀，唔改得任何嘢。',
    ]),
    P('**Viewer 網址：**[寄出之前喺度貼上 viewer 網址]'),
    LABEL('瀏覽器同裝置'),
    TABLE(['裝置', '瀏覽器', '備註'], [
        ['Windows 或者 Mac', 'Chrome 或者 Edge（建議）、Safari、Firefox', '有中鍵（滾輪）嘅滑鼠，用 3D 會容易好多'],
        ['iPad', 'Safari', 'Apple Pencil 可以畫 markup；建議打橫用'],
        ['iPhone', 'Safari', '最適合睇同讀；3D 會載一個輕啲嘅 model'],
    ]),
    LABEL('保密'),
    UL([
        '當 viewer 係 project folder 咁對待：只可以加 project 團隊入面嘅人。',
        '唔好分享密碼、唔好轉寄邀請 email，亦唔好喺團隊以外貼連結。',
        '截圖同 export 出嚟嘅 PDF，跟其他 project 文件一樣嘅規矩。',
    ]),
    H2('點樣串埋一齊'),
    P('BIM coordinator 由 Revit publish sheet 同 3D；團隊喺瀏覽器 review；issue 再返去 Revit 俾做 model 嘅人。'),
    IMG(),
    P('LWK Viewer 流程 · publish、review、喺 Revit 回覆'),
    OL([
        '**Publish。** 喺 Revit 撳 **Publish to Viewer**，會將揀咗嘅 sheet export 做 PDF，model（連 link）export 做快速 3D 格式，然後只上載有改動嘅檔案。可以每晚自動做。',
        '**準備。** Server 會幫每個 3D model 整一個俾手機同平板用嘅輕身版本，同埋讀晒每張 sheet 上面嘅字俾人搜尋。每次上載之後要幾分鐘。',
        '**Review。** 團隊用任何瀏覽器打開 Sheets、3D 或者 Dashboard。Markup 同 issue 會自動儲存，所有人都即刻見到。',
        '**回覆。** 被指派嘅人會喺 viewer 見到個 issue，喺 Revit 嘅 **LWK Issues** 視窗都見到；嗰度可以 zoom 過去，亦可以傳回覆同狀態返嚟。',
        '**關閉。** 開 issue 嘅人或者 project admin 將 issue 改做 Resolved，再改做 Closed。Dashboard 會跟住邊啲未完成、過咗期、喺邊個手上。',
    ]),
    P('圍住呢個流程：實際工作喺 **Tasks** 安排（可以由 issue 開 task，task 做完會幫手關 issue），喺 **Messenger** 討論（每個 project 有一個 channel，task 同 issue 更新會出喺度），再用 **Search** 搵返。**Projects** 版就將每個 job 串埋一齊。'),
    H2('快速上手：頭十分鐘'),
    P('登入、打開一張 sheet、喺 3D 睇返同一個位，再開一個測試 issue。'),
    OL([
        '**登入。** 打開 viewer 網址，輸入 email 同密碼，到時跟指示改咗個臨時密碼佢。',
        '**揀 project。** 用頂部嘅 project 名（如果你喺多過一個 project，會有下拉選單），或者喺 **Dashboard** 揀。',
        '**打開一張 sheet。** 喺 **Sheets** 撳左邊清單入面嘅 sheet，或者喺 **Search all sheets** 打房名、grid 或者 note。滾輪放大縮細，㩒住中鍵拖動，撳 **Fit** 睇成張圖。',
        '**去 3D。** 撳左上角嘅 **3D**。㩒住右鍵轉，㩒住中鍵移，滾輪放大縮細。Double-click 一個面就會 zoom 埋去。',
        '**睇一層。** 喺 **Floor plan** 下拉選單揀一層：model 會喺嗰層上面 1.2 m 切開，由上面望落去。**Page Up / Page Down** 上落一層；**Whole building** 返去 3D。',
        '**撳一件元件**，右邊嘅 **Selection** panel 會顯示佢嘅 property。',
        '**開一個測試 issue。** 撳 **Add issue**，撳一個面，打個標題例如「TEST - please ignore」，然後 **Save issue**。所有人都會喺 **Issues in 3D** 見到。',
        '**試吓 2D + 3D。** 返去 Sheets，打開一張平面圖，撳 **2D + 3D**；喺平面圖上面撳，3D 就會移去嗰度。',
        '**由佢開一個 task。** 打開個測試 issue，撳 **+ New task from this issue**，睇吓 list、負責人同限期啱唔啱，再撳 **Make the task**。',
        '**喺 Chat 打個招呼。** 打開 **Chat**，揀 project 嘅 channel，打 **#** 揀你個測試 task，再撳 **Send**。',
        '**搜尋。** 按 **Ctrl+K**（或者撳頂部個放大鏡），打 issue 標題入面一個字：issue、task 同你個訊息都會搵到。',
        '**做完記得刪除測試 issue 同 task：** issue 喺佢嘅詳情視窗撳 **Delete**，task 喺佢嘅視窗撳垃圾桶掣。',
    ]),
    H2('Dashboard 同 project'),
    P('Dashboard 係 project 嘅 issue 計分板：幾多個未完成、幾多個過咗期、喺邊個手上，同埋今個星期有乜改變。'),
    LABEL('四圍行'),
    UL([
        '每一版頂部都係同一排、同一個位置嘅頁面：**Projects**、**Sheets**、**3D**、**Board**、**Tasks**、**Chat**（有未讀訊息數目）同 **Dashboard**。右邊有：**Search** 放大鏡、**+ Task**（喺 Sheets 同 3D：將而家呢張 sheet 或者 3D 視圖放落 task）、**Admin**（只有 admin 見到）、**Account** 同 **Sign out**。手機上面呢排可以打橫碌。',
        '**Project 下拉選單**（Sheets、3D、Board、Dashboard）會列出 Projects 版嘅 project 名，例如「SKW · HKA-P-01681-ARC」。由幾個 model 組成嘅 project，例如 MOS Site 1 同 Site 2，會變成一組，下面列出佢嘅各部分。',
        '連線標籤會顯示 **online - 你個名**、**N waiting to save**（斷咗線；你嘅改動排緊隊，有返線就會送出）或者 **offline**。有改動等緊儲存嘅時候唔好 reload：排緊隊嘅嘢只會保留到你離開嗰版為止。',
    ]),
    LABEL('Dashboard 顯示乜'),
    TABLE(['部分', '話俾你知'], [
        ['篩選', '**Closed within**（Any time 至 Last 12 months）、**Type**、**Assigned to**、**Office**、**Only mine**、**Include "not an issue"**'],
        ['今個星期', '今個星期開咗、關咗、未完成同過咗期嘅 issue，同埋每個人手上未完成嘅 issue；**Send to Teams** 會貼去 project channel'],
        ['總結數字', 'Issues、Open、In progress、Resolved、Closed、Overdue、7 日內到期、未指派、平均開咗幾多日、平均幾多日關'],
        ['圖表', '每星期開同關嘅數目（最近 12 個星期），按狀態、類型、優先次序、喺邊度開（sheet 或者 3D）同 office 分'],
        ['責任表', '每個負責人手上未完成、進行中、過咗期同就快到期嘅數目，最舊嘅未完成 issue 同最後活動；撳一行就會篩選'],
        ['清單', '**Overdue**、**Due in the next 14 days**、**Recently changed**、**Going quiet**（14 日或以上冇郁過）'],
    ]),
    UL([
        '**Export CSV** 會下載篩選咗嘅 issue 俾 Excel 用。**Report** 會打開一份有相、可以列印嘅 issue 報告。',
        '呢版每 2 分鐘自動更新；撳 **Refresh** 即刻更新。',
        '**呢個 project 嘅 task：** 如果呢個 project 喺 Projects 版上面，Dashboard 亦會顯示佢喺每個團隊 list 入面嘅 task：未完成、過咗期，同埋做咗幾多個 sub-task。',
    ]),
    LABEL('通知'),
    UL([
        '**Email**（server 設定好 email 嘅話）：有人將你設做 task 負責人、喺 task 或者 chat @mention 你、或者你 follow 緊嘅 task 有新留言或者完成咗，都會 email 你；每日仲會收到一封，列出聽日到期同已經過咗期嘅 task。',
        '**Teams：** 如果 admin 已經連接咗 project 嘅 Teams channel，issue 開咗、指派咗、改狀態或者限期、或者有新留言，都會貼去嗰度。留言入面嘅 @mention 會變成 Teams 嘅 mention。',
        '每星期嘅總結可以貼去同一個 Teams channel（預設係星期一）。',
        '**Messenger：** project 嘅 channel 會用卡片顯示新 task、指派、完成同留言，同埋新開或者改咗嘅 issue。',
    ]),
]
