# 廣東話版 第四部分：Issue 同 BCF 到最尾

from blocks import *

PART = [
    H2('顧問嘅 model（IFC）'),
    P('其他公司（結構、MEP、室內、幕牆）嘅 model 可以同 project 自己嘅一齊睇。叫佢哋俾 **IFC**（IFC 2x3 或者 IFC4）：SketchUp、Revit、Tekla、ArchiCAD 同 Rhino 全部都出得，而且保留晒元件、屬性同真實座標。（「WebGL」係瀏覽器畫圖嘅方法，唔係用嚟交換嘅檔案格式。）'),
    TABLE(['用法', '點做'], [
        ['加入呢個 project 嘅 3D', '**Models** panel > **+ Consultant model (IFC)**：揀 .ifc，填名、公司同專業，撳 **Upload and convert**。Server 會轉換（有進度條），完成後就喺 **Consultant models** 出現'],
        ['疊另一個 project 嘅 model', '**+ Overlay another project**：揀一個你開得嘅 project 同佢其中一個 model。會用兩個 project 共用嘅 shared coordinates 擺位'],
        ['自己一版 3D', 'Admin 用 **New 3D project from IFC**（Admin 版）開。座標同乜都對唔上嘅 model 用：做一個獨立參考，之後一樣可以疊落其他 project'],
    ]),
    UL([
        '每個顧問 model 有剔格（你自己開／關）同一條可以調透明嘅 slider。',
        '**整體上色，方便比較：** 顧問 model 隔籬（同 **Models** 清單每個 model 隔籬）嘅小圓圈，可以將成個 model 變一隻顏色 - 紅、橙、黃、綠、青、藍、紫、灰或者任揀 - 例如自己 project 灰色、結構紅色。**↺ Original colour**（顏色選單入面，或者上咗色嘅 model 隔籬個 **↺**）變返原色；Models panel 頂部嘅 **↺ Reset colours** 一次過將所有 model 變返原色。會記喺呢部機，可以同透明 slider 一齊用，**White** 模式都保留顏色。',
        '用 **No coordinates: set in the middle** 擺位嘅 model，位置會為所有人記住，手機都一樣 - 手機載入嘅 link model 少啲，以前會因此計錯位置。',
        '**Place**（加佢嗰個人或者 project admin）幫所有人設定擺喺邊：**Shared coordinates**（有協調座標嘅顧問就係呢個）、**This model\'s origin**，或者 **No coordinates: set in the middle**；再用 **East / North / Up**（mm）同 **Turn**（°）一路睇一路手動移。**Save for everyone** 儲存；**Cancel** 放返原位。',
        '佢嘅元件一樣撳得，一樣可以開 issue。',
        '**×** 由 project 移除（加佢嗰個人或者 project admin）。',
    ]),
    H2('Issue 同 BCF'),
    P('Issue 係一個 markup 或者 3D 嘅一點，有標題、類型、負責人、到期日同對話；server 會幫佢編號（#N），同一個 issue 會喺 Sheets、3D、Dashboard 同 Revit 出現。'),
    H3('開 issue'),
    TABLE(['喺邊', '點做'], [
        ['喺 sheet 上面', '將頂部轉做 **Issue** 再畫 markup；或者揀一個 markup 撳 **Issue**；或者右鍵撳佢揀 **Raise issue**。會自動夾一張清晰嘅圖則截圖：直接由 PDF 用大約 200 dpi 畫出嚟，唔受你放大幾多或者電腦嘅速度設定影響。'],
        ['喺 3D', '撳 **Add issue**，然後撳個位（iPad：㩒住）。鏡頭、section 同隱藏咗嘅元件會一齊儲存，仲會夾一張截圖。**Mark up snapshot** 俾你喺張相上面畫嘢（cloud、箭咀、文字等等）。'],
    ]),
    P('填好 issue 視窗，然後撳 **Save issue**：'),
    TABLE(['欄', '備註'], [
        ['**Title**', '一定要填，最多 120 個字。寫清楚咩問題、喺邊，例如「L12 corridor: fire door swing clashes with riser」'],
        ['**Type**', 'General、Design、Coordination、Clash、Fire safety、Statutory / BD、Structure、MEP、Facade、Drawing error、Query / RFI'],
        ['**Description**', '咩問題、你預期係點、有咩參考'],
        ['**Assign to**', '揀一個 project 成員（或者打個名）'],
        ['**Due**', '幾時要有答覆'],
        ['**Status**', 'Open、In progress、Resolved、Closed'],
        ['**Priority**', 'Low、Normal（預設）、High、Critical'],
        ['**Template**', '載入一套儲存咗嘅欄位；**Save as template** 將而家嘅分享俾成個 project'],
    ]),
    H3('跟進 issue'),
    UL([
        '喺清單撳一個 issue（或者 3D 入面佢支 pin）打開佢。喺 3D，視圖會返去開 issue 嗰個人見到嘅樣：同一個眼位同方向、section box 連佢嘅角度（或者 section plane）、隱藏咗嘅元件、平行定透視，同 floor plan。**Show in view** 同 issue 連結都一樣。',
        '**喺 Revit**（LWK Issues > **Go to**）：用 viewer 普通鏡頭、或者行緊（walk）時開嘅 issue，會喺一個透視鏡頭視圖 **LWK Issue - <你> (camera)** 由同一個眼位打開，連埋同一個 section box，唔再係由外面睇成棟樓。',
        '喺 issue 視窗：改標題同欄位、**Add photo**（地盤相，可以一次加幾張），喺 **Add a comment** 寫低再撳 **Comment**。打 **@** 可以 mention project 成員。',
        '**Show in view** 返去嗰個位；**Show in 3D** 喺嗰度打開 3D 版。',
        '**Not an issue** 會連一個人人睇到嘅原因閂咗佢；同一個掣可以重開。',
        '**Delete** 會幫所有人刪除。Member 只可以刪自己嘅 issue；project admin 刪得任何一個。',
        '**Revit element**（3D issue）：開 issue 嗰個元件，有 **Copy Revit IDs**、**Show in 3D** 同 **Show in Revit**。',
        '**Tasks：** 連住呢個 issue 嘅 task，有負責人同到期日。**+ New task from this issue** 開一個（睇「Issue 同 task 連埋一齊」）；**Send to chat** 將 issue 貼去一個 chat。',
        '將狀態改做 **Resolved** 或者 **Closed** 再撳 **Save**：如果 issue 嘅 task 仲未完成，viewer 會問你要唔要順手剔佢哋做完成。',
    ]),
    H3('狀態：邊個做乜（團隊做法）'),
    TABLE(['狀態', '邊個改', '意思'], [
        ['Open', '開 issue 嘅人', '開咗，等負責人跟'],
        ['In progress', '負責人', '做緊'],
        ['Resolved', '負責人', '改好或者答咗；等開 issue 嘅人檢查'],
        ['Closed', '開 issue 嘅人或者 project admin', '檢查過，搞掂'],
    ]),
    H3('搵 issue'),
    UL([
        '**Sheets：** 右邊 panel 列出 **All / Issues / Comments**，可以按 Sheet、Status、Assigned to、Raised by、View、Issue type 或者 Markup type 分組，有 **Search** 格。右鍵撳一項可以打開、喺 sheet 或者 3D 顯示，或者改狀態。',
        '**3D：** **Issues in 3D** 按 Status、Floor、Issue type、Assigned to、Raised by 或者 Model 分組。**Sheet issues** 會將喺 sheet 開嘅 issue 用菱形顯示喺 model 入面。**Hide issues** 隱藏啲 pin（乜都冇刪）。',
        '**Dashboard：** 篩選、過咗期清單同責任表（睇「Dashboard 同 project」）。',
    ]),
    H3('BCF：同 Revit、Navisworks 等等交換 issue'),
    UL([
        '**Export BCF**（3D 版）同 **BCF**（Sheets 版）會下載一個 BCF 2.1 檔，入面有每個 issue 嘅標題、狀態、優先次序、日期、作者、負責人、描述、鏡頭、揀咗嘅元件同截圖。冇 issue 嘅普通 comment 唔會包括，issue 類型、comment 對話同加咗嘅相都唔會包括。',
        '揀咗嘅元件會連佢嘅 IFC GUID **同 Revit ElementId**（AuthoringToolId）一齊寫入，所以 Autodesk BCF Manager、BCFier 同 Revizto 呢啲 Revit BCF 工具會喺 Revit 揀中佢。',
        '**Import BCF**（只限 3D 版）讀 Revit、Navisworks、Solibri 或者 ACC 嘅 BCF 2.0、2.1 同 3.0。佢會先問個檔用邊套座標：除非你知，否則揀 **Work it out (recommended)**。已經 import 過（同一個 ID）嘅 issue 會跳過。',
    ]),
    H2('Issue 同 task 連埋一齊'),
    P('Issue 講咩出咗問題；task 講邊個幾時之前改好。兩樣連埋一齊，每一邊都會問你要唔要順手閂埋另一邊。'),
    UL([
        '**由 issue 開 task：** 喺 issue 視窗撳 **+ New task from this issue**。呢個 project 嘅 task list 同 group 會排先，負責人係 issue 嘅 **Assigned to**，到期日同 issue 一樣。Issue、佢嘅檔案同 Revit 元件都會放落個 task。剔 **Open the task when made** 就會開完即刻去個 task。',
        '**Task 完成 → issue：** 當你 **Mark complete** 一個 task，而佢連住嘅 issue 仲未閂，Tasks 會問 **Resolve its issues too?** 剔要改嘅，揀 Resolved 或者 Closed。改法同你喺 viewer 自己改一樣：有歷史、email、chat 卡片，同一條寫明係邊個 task 嘅 comment。',
        '**Issue 解決 → task：** 將 issue 改做 Resolved 或者 Closed 再 **Save**；如果佢嘅 task 仲未完成，viewer 會問你要唔要剔佢哋做完成。啲 task 嘅 activity 都會多一行記錄。',
        'Task 視窗會顯示每個相連 issue 而家嘅狀態；task 清單會顯示 **#n open** 或者 **#✓**。',
    ]),
    H2('Revit 元件'),
    P('3D issue 會記住開 issue 嗰個 Revit 元件：**ElementId**、**UniqueId**、IFC GUID、category、family / type 同樓層。由 LWK add-in publish 嘅 model 全部都知；舊啲嘅 model 只有 IFC GUID。'),
    TABLE(['想', '咁做'], [
        ['而家喺 Revit 揀中佢', '**Copy Revit ID**（或者 **Copy Revit IDs**），然後喺 Revit 用 **Manage > Select by ID** 貼上。今日已經用得，唔使改 add-in'],
        ['喺 3D 睇佢', '**Show in 3D**：3D 版會揀出嗰啲元件再 zoom 埋去'],
        ['叫 Revit 揀佢', '**Show in Revit** 叫 LWK add-in 喺 Revit 揀中佢。Add-in 未支援之前，會改為 copy 啲 id 俾你用 Select by ID'],
        ['交俾同事', '喺 3D 版揀元件再撳 **+ Task**：佢哋會放落 task 做 **Elements to change**，有同樣嘅掣'],
        ['傳去其他軟件', '**Export BCF**：Revit 嘅 BCF 工具會用 ElementId 揀中個元件'],
    ]),
    H2('搜尋'),
    P('一個格搵晒所有嘢：喺任何一版按 **Ctrl+K** 或者 **/**，或者撳頂部個放大鏡。'),
    UL([
        '佢會搵 **project**、**task**（標題、描述、T-12）、**issue**（#12、標題、描述、sheet、負責人、Revit 元件同 id）、**sheet**、儲存咗嘅 **3D 視圖**、**訊息**，同 task 同 issue 上面嘅**檔案同連結**。',
        '打一個或者幾個字；每個字都要對到。結果按種類分組；↑ ↓ 同 **Enter** 打開，**Esc** 閂。',
        '你只會見到你有權打開嘅嘢。個格空白嗰陣會列出你最近搜尋過嘅。',
    ]),
    H2('離線工作'),
    P('喺地盤冇訊號嘅時候，下載咗落部機嘅 project 照樣用得：sheet、3D model、issue 同 markup。'),
    OL([
        '有網絡嗰陣，打開個 project，撳頂部嘅 **Offline**，再撳 **Download for offline**。下載會顯示進度，斷咗可以繼續。',
        '冇網絡嗰陣，頂部會寫 **Offline - copy of <日期>**。可以睇 sheet 同 model、開同回覆 issue、畫 markup。',
        '離線做嘅改動會喺部機度等（**N changes waiting**），網絡返嚟就會自己 upload（**All changes uploaded**）。',
    ]),
    UL([
        'Dashboard、Admin、Board、Tasks、Messenger、同舊版本比較同加 PDF 都要有網絡。',
        '喺 iPad 同 iPhone，先 **Add to Home Screen**：Safari 可能會清走幾個禮拜冇開過嘅網站，但 Home Screen 嘅 app 會保留。',
    ]),
    H2('手機同平板'),
    P('同一個網址喺 iPad 同 iPhone 嘅 Safari 都用得；viewer 會認出部機，載入輕啲嘅 3D model，等部機記憶體夠用。'),
    LABEL('手機或者平板有乜唔同'),
    UL([
        '側邊 panel 變成抽屜：左邊 **☰ Models** / **☰ Sheets**，右邊 **ⓘ Details** / **Issues**。撳抽屜外面就閂。Details 上面有粒點即係揀咗嘢。',
        '3D 會載入每個 model 嘅手機版，每次 publish 之後 server 會整。大 project 嘅幾何會跟住你望邊度一嚿嚿攞（「streaming」），先粗後幼。',
        '**Light mode** 開咗：重複嘅標準層只會喺你望緊嘅附近載入。',
        '傢俬呢啲細嘢只會喺鏡頭附近畫，遠嘅部分用簡化咗嘅形狀。',
        '切到嘅實體有橙色 hatch，但冇啡色輪廓線。',
        '頂部可以打橫碌：掃一掃就見到 Board、Tasks、Chat 同 Dashboard。',
        '**Search** 會佔滿成個畫面。喺 **Messenger**，撳一下訊息就出佢嘅掣；Enter 係換行，撳圓形掣先發送。',
    ]),
    LABEL('手勢'),
    TABLE(['手勢', '3D', 'Sheets'], [
        ['一隻手指', '轉', '用而家嘅工具畫（用過 Apple Pencil 之後就係 pan）'],
        ['兩隻手指', '捏 zoom，拖 pan', '捏 zoom，拖 pan'],
        ['Double tap', '對準嗰個面', '-'],
        ['㩒住', '喺嗰點開新 issue', '右鍵選單'],
        ['兩隻／三隻手指 tap', '-', 'Undo / redo'],
    ]),
    LABEL('貼士'),
    UL([
        'iPad 打橫用，畫圖嘅位最多。',
        '如果個 model 啱啱幾分鐘前先 publish，手機版可能仲整緊；版面會問你要唔要整，等幾分鐘再試。',
        '如果 Safari 自己 reload 個版，即係部機記憶體唔夠：喺 **Models** 唔剔你唔使用嘅 model，留喺一層，再報告（睇「解決問題同常見問題」）。',
    ]),
    H2('Performance panel 同設定'),
    P('3D 版右下角嘅 **Performance** 連結會打開載入時間、frame rate 同記憶體，仲有幾個設定；**Copy** 會將成份報告放入 clipboard，報告問題嗰陣可以貼落 email 或者 Teams。'),
    TABLE(['設定', '選擇', '做乜'], [
        ['**Streaming**', 'automatic / on / off', '大 model 跟住視圖需要一嚿嚿攞（automatic = 手機同平板開）'],
        ['**Memory budget**', 'automatic / 150 至 1500 MB', '部機留幾多幾何先放走睇唔到嘅部分'],
        ['**Drawing with**', 'WebGL（標準）/ WebGPU（試驗）', '繪圖方法；轉嘅時候會 reload。除非叫你試，否則用 WebGL'],
        ['**While moving**', 'follow the frame rate / always full quality', '郁嘅時候 frame rate 跌，就畫輕啲嘅郁動畫面；停定嘅畫面永遠係全質素'],
    ]),
    P('Streaming 同 memory budget 要 reload 個版先生效。狀態列亦會顯示即時 frame rate、畫咗幾多三角形同顯示卡記憶體；「moving step 1 to 4」即係用緊輕啲嘅郁動畫面。'),
    LABEL('載入速度'),
    UL([
        'Viewer 嘅檔案會壓縮咗先傳（3D library 由 4.8 MB 變 0.7 MB），而且你個瀏覽器會留低：由第二次開始，版面喺你自己部電腦打開，只有資料由 server 嚟。',
        '每一版載入嗰陣會一次過攞晒佢要嘅資料。Messenger 同 Projects 版仲會即刻顯示上次見到嘅嘢，然後先更新。',
        'Viewer 更新之後，改咗嘅檔案會自己重新攞；唔會新舊混埋。',
    ]),
    H2('俾 BIM coordinator：由 Revit publish'),
    P('一個掣 **Publish to Viewer** 就會 export sheet 同 3D model 再 upload；其他掣係俾你逐步自己做，或者夜晚自動做。'),
    H3('設定（每部電腦一次）'),
    UL([
        '安裝 LWK pyRevit extension。佢會加一個 **LWK** tab，有 **Viewer & Issues** panel：**Publish to Viewer**、**LWK Issues** 同 **Viewer tools** 下拉選單。',
        'Sign in 一次（喺 **LWK Issues** 或者 **Publish**）。登入會保留一年，夜晚 upload 都照做得。',
        'Upload 去現有 project 你要係佢嘅 **project admin**；新 project 名要 **site admin**。',
    ]),
    H3('Publish to Viewer'),
    OL([
        '喺 Revit 打開 model，撳 **Publish to Viewer**。',
        '**Where：** 揀 **Viewer project**（或者打個新名：英文字母、數字、- 同 _），檢查 **Server** 顯示「signed in」，同埋 **Export folder**。',
        '**What：** 剔 **3D model (fast format, with its linked models)**，揀細節：**Coarse (lightest)**、**Medium (recommended)** 或者 **Fine (most detail)**。剔 **Sheets**，揀 **All sheets**、**A Revit sheet set** 或者 **These sheets**。**Keep sheets published before** 會保留之前 publish 過、但唔喺今次選擇入面嘅 sheet。',
        '**Then：** **Send to the viewer server (only what changed)**、**Open it in the browser when done**，可以揀 **Publish this model again every night at** 01:00（想嘅話只限星期一至五；只限 ACC model）。',
        '撳 **Publish**。你揀嘅嘢會為呢個 model 記住。Revit model 唔會被改或者儲存。',
    ]),
    P('Upload 完之後 server 要幾分鐘整手機版同讀 sheet 嘅字。Server 會保留每張 sheet PDF 最近 12 個版本（俾 **Compare** 用），同每個 3D model 最近 2 個（俾 **Compare with previous export** 用）。'),
    H3('Viewer tools 下拉選單'),
    TABLE(['掣', '用嚟'], [
        ['**Fast 3D Export**', '只 export 3D model（同 link），用 fast 格式；sheet 保留'],
        ['**Export Viewer**', '自己 export sheet 同 manifest（舊 IFC 方法）'],
        ['**Upload Now**', '再將上次 export 傳去 server'],
        ['**Add Model**', '登記一個 ACC model 做自動 export：sheet、IFC schema、唔要嘅 category、標準層組'],
        ['**Run Export**', '即刻 export 同 upload 所有登記咗嘅 model（Shift-click：只做打開緊嗰個）'],
        ['**Night Export**', '排每晚或者平日夜晚做、取消排程，或者睇狀態同 log'],
        ['**Export Link**', 'Export 一個自動 export 開唔到嘅 link（例如舊版本嘅 cloud model）'],
        ['**Link Places**', '將每個 link instance 嘅位置寫入 export folder'],
        ['**Test Links**', '快速檢查放咗多過一次嘅 link'],
    ]),
    P('**夜晚 export 需要：** 部電腦開住同登入咗（鎖咗 screen 冇問題）、排咗嘅時間 Revit 要閂咗、Revit 登入咗 Autodesk。每個 model 預大約 15 分鐘。Log 喺 %APPDATA%\\LWK\\nightly。'),
    UL([
        'Model 嘅每個 workset 都會逐個名打開，冇 load 嘅 link 會 load 返。如果仲有 workset 閂住，或者 3D model 出咗嚟係空嘅，viewer 會**保留上次好嘅 3D model**（sheet 照傳），log 最尾寫 **result FAILED** 同原因。',
        '已知嘅對話框會自動答，唔會令夜晚 export 停住：DWG 嘅 paper space 冇嘢（Yes）、DWG import 嘅通知（Close），同開 Revit 時嘅 **External Tools - Add-in Assembly Not Found**（由 launcher 嘅 watcher 撳 Close）。每個對話框都會寫入 nightly\\dialogs.log。最好係喺嗰部電腦修好或者移除壞咗嘅 add-in。',
    ]),
    H3('Revit 入面嘅 LWK Issues 視窗'),
    UL([
        '列出一個 project 喺 viewer 嘅 issue：**Show** 未完成同做緊、派俾我嘅，或者全部；可以搜尋；欄有 #、Title、Type、Status、Priority、Assigned to、Due、Where。',
        '**Go to issue**（或者 double-click）會打開一個私人 3D 視圖「LWK Issue - 你個名」，有 section box 圍住個 issue，或者 zoom 去 sheet。隔籬有 **Open its plan view** 同 **Open in web viewer**。',
        '**Place pins for the list** / **Remove pins** 喺 workset「LWK Issues」加「LWK #n」標記。**Clouds on sheets** 喺 revision「LWK Viewer issues」下面加 revision cloud。',
        '揀個狀態及／或打個 comment，然後 **Send to viewer**：會用你個名出現喺網上 viewer。',
    ]),
    H3('Revit 元件同 LWK add-in'),
    UL([
        '喺 publish 咗嘅 model 3D 入面開嘅每個 issue 都帶住元件嘅 ElementId 同 UniqueId。Review 嘅人可以 copy 啲 id 用 **Manage > Select by ID**，BCF export 會當 AuthoringToolId 帶埋佢哋。',
        'Viewer 入面嘅 **Show in Revit** 會喺 server 留低一個要求俾 add-in 攞；add-in 亦可以將 Revit 入面揀咗嘅嘢傳去 viewer。Add-in 要做乜寫咗喺 **server/REVIT_ADDIN_API.md**，俾負責維護佢嘅人睇。',
    ]),
    H2('俾 admin 嘅'),
    P('Project admin 喺 **Admin** 版管理自己 project 嘅人同設定；site admin 仲管理 account、所有 project、回收站同裝置報告。'),
    H3('角色'),
    TABLE(['角色', '可以'], [
        ['**Viewer**', '乜都睇得；唔可以加或者改 issue 同 comment'],
        ['**Member**', '開同改 issue 同 comment；只可以刪自己嘅'],
        ['**Project admin**', 'Member 做得嘅全部，加上管理 project 成員、改或者刪任何嘢、無視 layer 鎖、upload model'],
        ['**Site admin**', '所有 project；加、停用同 reset account；開、刪同還原 project'],
    ]),
    P('每個 project 一定要留最少一個 project admin。'),
    H3('Project 同成員'),
    UL([
        '**Add people to this project：** 搜尋，用 **team**、**office** 或者 **company** 篩選，剔幾個人（或者 **Select all shown**），揀 Role 再撳 **Add N people**；或者填 **Someone without an account yet**（Email、Name、Office、Company、Role）再撳 **Create and add**。臨時密碼只會顯示**一次**。',
        '用 **Email invitation**（打開你自己嘅 Outlook）或者 **Copy invitation** 傳俾佢。佢第一次 sign in 要揀自己嘅密碼。',
        '喺成員表改角色，或者 **Remove** 一個人（佢嘅 issue 同 comment 會留低）。',
        '**Teams channel：** 貼 Teams Workflow webhook 網址，**Save**，**Send a test**，再揀每週總結嘅日子同鐘數（香港時間）。',
        '**Markup layers：** 每個 layer 設定邊個改得（所有成員、只限 project admin，或者指定嘅人）、邊個睇得到，同埋開頭係咪隱藏。',
        '**Phones and tablets：** 如果手機話冇手機版，**Prepare this project now** 會重新整；**Show progress**（site admin）顯示 server 背後做緊嘅嘢。',
    ]),
    H3('Projects（Admin > Projects and members）'),
    UL([
        '**+ New project**：**Project name**（例如 HKA-P-01681-ARC - SKW；code 會由佢攞）、**Code**、**Status**、**Group / team**、**Owners**，同 **Folders and files**（OneDrive、SharePoint 或者 ACC 連結）。**Import** 讀由 Lark Base 或者 Excel export 嘅 project 表。',
        '**Models and sheets：** 顯示呢個 job 嘅 viewer project（export folder）。一個 job 有幾個 Revit model 同 sheet set（例如 Site 1 同 Site 2），就 Ctrl+click 揀幾個。揀一個其他地方用緊嘅會搬嚟呢度；server 單獨為佢整嘅項目會移除，佢嘅 task group 會跟住搬過嚟。',
        '成員屬於每一個部分（係佢哋令人可以打開嗰個 model）。有幾個部分嘅話，成員表上面會出 **Part** 選擇。',
        '**Remove from Projects** 將一個 job 拎走出 Projects 版；佢嘅 task、issue、model 同檔案都會留低。',
    ]),
    H3('只限 site admin'),
    UL([
        '**People：** 加 account、**Reset password**、**Make / Remove site admin**、**Deactivate / Reactivate**（會喺所有地方 sign out 嗰個人）、**Edit**、**Delete**（整錯咗嘅 account 用）。',
        '**Delete project ...：** 打個 project 名確認。Model、sheet、issue、markup 同成員會搬去 server 嘅回收站；喺回收站清單撳 **Restore** 會全部放返，只要個名未被再用。',
        '**Devices：** 3D 版由每部裝置傳嚟嘅報告：載入咗乜、最高記憶體、frame rate、卡頓同 crash。篩選 crash 或者手機同平板，就知 viewer 喺邊度辛苦。',
        '**Server：** email 要 server 設定好 LWK_SMTP_。如果 server 前面嘅 proxy 處理唔到壓縮咗、瀏覽器保留嘅檔案，用 --plain-assets 開 server（或者喺 run.bat 設 PLAIN_ASSETS=1）。',
    ]),
    H2('解決問題同常見問題'),
    P('大部分問題都係舊嘅 cache 版面、網絡慢或者部機記憶體唔夠；下面個表寫咗第一樣要試嘅嘢。'),
    TABLE(['問題', '試吓咁'], [
        ['啲嘢好似舊咗，或者冇咗新功能', '睇左上角「LWK Viewer」隔籬嘅版本；按 Ctrl+F5（Windows）或者 Cmd+Shift+R（Mac）。iPad 就閂咗個 tab 再開過'],
        ['「Wrong email or password」', '檢查 email；叫 admin **Reset password**。試咗 10 次之後要等 15 分鐘'],
        ['「You are not a member of this project」', '叫 project admin 加你'],
        ['我加唔到或者改唔到 issue', '你喺呢個 project 係 **Viewer**；叫 project admin 俾你做 Member'],
        ['「N waiting to save」', '你個網絡斷咗。留住個版唔好閂；網絡返嚟就會儲存'],
        ['最新嘅 sheet 或者 model 唔見', 'Publish 可能仲做緊，或者 server 準備緊；等幾分鐘再 reload'],
        ['電腦上面 3D 好慢或者一頓頓', '唔剔唔使用嘅 model、用 floor plan、檢查 **While moving** 係「follow the frame rate」'],
        ['iPad 或者 iPhone 自己 reload 個版', '記憶體唔夠：開少啲 model、留喺一層、開住 **Light mode**；傳 Performance 報告'],
        ['喺 section 入面撳唔到一個元件', '只有切面睇得到嗰邊揀得；郁吓切面或者用 Model browser'],
        ['量度 snap 錯嘢', 'Zoom 近啲；停定等 label 顯示 **corner**、**midpoint** 或者 **edge**'],
        ['Revit link 唔見咗或者放錯位', '檢查 **Apply link transforms** 開咗；話俾 BIM coordinator 知'],
        ['轉咗 WebGPU 之後版面唔同咗', '喺 Performance 撳 **Drawing with** 轉返 WebGL（或者喺網址加一次 &gpu=webgl）'],
        ['經 VPN 或者喺屋企開版面好慢', '第二次會快好多（啲檔案會留喺你個瀏覽器）。如果第一次開一直都慢，叫 IT 喺 server 嘅 proxy 開 HTTP/2'],
        ['搜尋乜都搵唔到', '最少打 2 個字；每個字都要對到。你只會見到你係成員嘅 project、list 同 chat'],
        ['「Revit\'s LWK add-in is not listening」', '已經改為 copy 咗啲 id：喺 Revit 用 **Manage > Select by ID** 貼上'],
        ['WhatsApp import：「does not look like a WhatsApp chat export」', '用 WhatsApp 嘅 **Export chat** 檔（.txt 或者 .zip），唔好用截圖或者轉發嘅訊息'],
        ['Task 或者訊息連結打開唔到嘢', '你可能唔係嗰個 list、chat 或者 project 嘅成員；問佢嘅 owner'],
        ['訊息或者 chat 冇 Delete', '訊息只有發嘅人刪得。Group 由佢嘅 admin 刪，project channel 同 topic 由 project 嘅 admin 刪'],
    ]),
    P('**報告問題嗰陣**請傳：project、版面（Sheets 定 3D）、你部機同瀏覽器、你做咗乜、截圖，3D 版就加埋 **Performance → Copy** 報告。'),
    LABEL('常見問題'),
    UL([
        '**會唔會改到 Revit model？** 唔會。Publish 只係讀個 model。只有 LWK Issues 視窗會加 pin 或者 cloud，而且係你叫佢先會做。',
        '**邊個睇到我嘅 markup？** Project 所有人，除非個 markup 喺 admin 限制咗嘅 layer 上面。',
        '**會唔會發 email？** 會，只要 server 設定好 mail：派 task、@mention、你 follow 緊嘅 task 有 comment 同完成，仲有每日到期 task 清單。Teams 照舊會 post。',
        '**可唔可以離線用？** 可以，用下載咗落部機嘅 project（睇「離線工作」）。短暫斷線都冇問題：改動會等住，網絡返嚟就儲存。',
        '**Messenger 係咪取代 WhatsApp？** 佢係用嚟做 project 嘢，就喺圖則同 task 隔籬。訊息可以傳去 WhatsApp，亦可以由 WhatsApp 帶入嚟，但兩邊唔會自動同步。',
        '**顧問用唔用得？** 用得，用佢哋自己嘅 account，通常只係嗰個 project 嘅 **Viewer** 或者 **Member**。',
    ]),
    H2('快捷鍵一覽'),
    P('印咗呢個表，或者頭一個禮拜放喺 screen 隔籬。'),
    TABLE(['喺邊', '鍵或者掣', '做乜'], [
        ['3D', '右掣拖', '轉'],
        ['3D', '中間掣拖', 'Pan'],
        ['3D', '滑鼠轆', '向住游標 zoom'],
        ['3D', 'Double-click', '對準嗰個面'],
        ['3D', '右鍵撳（唔拖）', '選單，同將轉嘅中心搬去嗰度'],
        ['3D', 'Page Up / Page Down', '上一層／下一層'],
        ['3D', 'Esc', '取消量度、停止行、閂選單'],
        ['3D 量度', 'Shift', '下一點開／熄 Straight'],
        ['3D 行', 'W A S D、↑ ↓', '行同打側行'],
        ['3D 行', '← →', '轉身'],
        ['3D 行', 'Shift / Q / E', '快啲／降／升（Gravity 熄咗）'],
        ['Sheets', '滑鼠轆／中間掣拖', 'Zoom / pan'],
        ['Sheets', 'Page Down / Page Up', '下一張／上一張 sheet'],
        ['Sheets', 'V / H', 'Select 工具／Pan 工具'],
        ['Sheets', 'Enter、Esc、Backspace', 'Polyline 完成、結束，或者刪最後一點'],
        ['Sheets', 'Delete', '刪揀咗嘅 markup'],
        ['Sheets', 'Ctrl+A', '揀晒張 sheet 嘅 markup'],
        ['Sheets', 'Ctrl+C / Ctrl+V', 'Copy／貼 markup（貼去另一張 sheet 都得）'],
        ['Sheets', 'Ctrl+Z / Ctrl+Y', 'Undo / redo'],
        ['Sheets', 'R / Shift+R', '揀咗嘅順時針／逆時針轉 90°'],
        ['Sheets compare', 'N / Shift+N', '下一個／上一個改動'],
        ['每一版', 'Ctrl+K 或者 /', '搜尋所有嘢'],
        ['搜尋', '↑ ↓、Enter、Esc', '移動、打開、閂'],
        ['Tasks', 'K / J', '上一個／下一個 task'],
        ['Messenger', 'Enter / Ctrl+Enter', '換行／發送'],
        ['Messenger', '@ # ! $ %', 'Mention 人／連結 task、issue、sheet、3D 視圖'],
        ['Messenger', 'Ctrl+Enter / Esc（改緊訊息）', '儲存／取消改訊息'],
        ['Messenger', 'Ctrl+B / Ctrl+I / Ctrl+Shift+X', '粗體／斜體／刪除線'],
    ]),
    H2('意見同先試乜'),
    P('呢個係試用版：請試吓下面啲嘢，話俾我哋知乜嘢好用、乜嘢搞唔清、仲欠乜。'),
    UL([
        '☐ Sign in 同改密碼',
        '☐ 搜尋一個房名或者 note 搵一張 sheet',
        '☐ 喺 sheet 上面畫一個 cloud 加文字，再變成 issue',
        '☐ 喺 3D 打開同一個位置，切一個 floor plan',
        '☐ 開住 **Straight**，喺 plan 量一間房牆到牆',
        '☐ 喺 3D 開一個 issue，派俾同事，再用 @mention 寫 comment',
        '☐ 試 **2D + 3D**，一路行走廊一路睇 plan',
        '☐ 喺 iPad 或者 iPhone 打開 viewer 睇一層',
        '☐ 由你嘅測試 issue 開一個 task，然後喺 Tasks 版完成佢同解決個 issue',
        '☐ 喺你 project 嘅 channel 發一條有 # task 同 $ sheet 連結嘅訊息',
        '☐ 喺你嘅 project channel 開一個 topic，pin 一條訊息，再發一個 poll 同一個 event',
        '☐ 用 Ctrl+K 搵你嘅測試 issue',
        '☐ 喺 3D 撳一個元件，撳 Copy Revit ID，再喺 Revit 用 Select by ID 揀中佢',
        '☐ 試完刪咗你嘅測試 issue 同 task',
    ]),
    P('意見、問題同問題報告請傳去 [名 / Teams channel]。同速度或者 crash 有關嘅，請夾埋 Performance 報告。'),
]
