# 廣東話版 第二部分：Projects、Tasks、Board、Messenger

from blocks import *

PART = [
    H2('Projects 項目'),
    P('**排序：** project 按狀態排 - **Active** 先，跟住 **On hold**、**Completed**、**Archived** - 同一狀態再按名排。Projects 版同所有 project 選單（Sheets、3D、Board、Dashboard、Folders、Messenger）都用呢個次序。喺 Projects 版撳欄目標題（Project、Status、Tasks、Completion、Overdue、Issues）或者用 **Sort** 可以轉其他排法；再撳一次就倒轉。會記住你嘅選擇。'),
    P('Sheets、3D、Board 同 Dashboard 頂部嘅 project 選單分開兩個：先揀 **project**（名 · 編號），再揀**佢嘅 model 或者 sheet set**（例如 Site 1／Site 2，或者 Sheets 版嘅「Revit sheets」同每個上載咗嘅 PDF set）。'),
    P('喺 project 嘅資料欄，**Project information** 可以記低 project no.、client、地址、建築類型、地盤面積、GFA、層數、階段、開始同完成日期同簡介（**Edit**，project owner 同 admin 先改得）。撳或者拖一張相落資料欄頂部，就可以俾個 project 一張**相**，清單入面都會見到。'),
    P('**Projects** 版列出團隊嘅 job，每個 job 嘅人、圖則、model、task、issue、檔案同 chat 都喺同一個地方。呢版係俾人睇嘅；admin 喺 **Admin > Projects and members** 設定 project（撳 **Manage** 掣會帶你去）。'),
    LABEL('清單'),
    TABLE(['欄', '顯示'], [
        ['Project', '簡稱同編號，例如 SKW · HKA-P-01681-ARC'],
        ['Open', '**Sheets**、**3D** 同 **Dashboard** 掣。由幾個 model 組成嘅 project（MOS Site 1、Site 2），每個掣都會彈出一個細選單俾你揀邊部分'],
        ['Tasks', '進度（做咗幾多／總數）、過咗期嘅 task 同未完成嘅 task，嚟自每個有呢個 project group 嘅團隊 list'],
        ['Issues', '按狀態分色嘅 issue 條，同埋未完成／總數；過咗期嘅會用紅色。會加埋 project 所有 model'],
        ['Folders', 'OneDrive、SharePoint 或者 ACC 嘅 folder'],
        ['Chat', 'Messenger 入面 project 嘅 channel，同埋未讀訊息'],
    ]),
    UL([
        '頂部可以搜尋 project 或者人名，亦可以按狀態篩選。',
        '撳一行睇**詳情**：按團隊分嘅成員、按狀態分嘅 issue（撳個數字會打開 Dashboard）、task 連 sub-task，同埋 **Models and sheets**：每個部分都有自己嘅 Sheets、3D 同 Dashboard 連結。',
        '**一個 project，幾個 model。** 一個 job 如果 export 做幾個 Revit model 同 sheet set，仍然係一個 project，分開幾個部分。成員係所有部分嘅人加埋，issue 數目會加埋所有部分，project 下拉選單會將佢顯示做一組。',
    ]),
    H2('Tasks 工作'),
    P('**Tasks** 係團隊嘅 task list，取代 Lark Tasks，同圖則、model 同 issue 連埋一齊。'),
    H3('List、group 同睇法'),
    UL([
        '**Task list** 屬於一個團隊（例如 LWK-MANILA）。List 入面嘅 **group** 通常就係各個 job（SKW、Kai Tak 2A3 ...）。連咗 project 嘅 group 會有 **Project**、**Sheets** 同 **Dashboard** 掣；喺 **...** > **Groups and projects** 連接。',
        '左邊嘅**快速存取**：**Owned**（自己未完成嘅 task）、**Subscribed**、**All**、**Created**、**Assigned**（你派俾人嘅）同 **Completed**，跨晒所有你睇得到嘅 list。**People** 按團隊、office 或者公司顯示成個機構，同每個人未完成同過咗期嘅 task。',
        '**List：** 分組嘅表。直接喺度改；撳 ▸ 打開 sub-task；拖住一行可以排次序或者搬去另一個 group。有連住 issue 嘅 task 會顯示 **#2 open**，全部 issue 解決咗就變 **#✓**。',
        '**Kanban：** 一行行卡片；拖張卡去另一行。成塊 board 跟視窗咁高，所以左右嘅 scroll bar 永遠喺畫面底，唔使拉到最底先見到；**Shift + 滑鼠轆**、拖 board 嘅空位，或者兩邊嘅 **‹ ›** 掣都可以左右捲。',
        '**Gantt：** 時間線上面嘅橫條；拖成條，或者拖佢兩頭改日期。每次改之前會彈出 **Change the dates?** 問你：**Save** 先會儲存，**Cancel** 條 bar 就返原位（剔 **Don\'t ask again today**，呢部機今日就唔再問）。圖例會解釋啲顏色；milestone 係金色。',
        '**Dashboard：** 總數、完成、未完成同過咗期，按負責人、按 project、平均用幾耐同就快到期。**Activities：** 所有改動，邊個改。',
        '可以按負責人同優先次序篩選、排序、**Group by**，同用 **Customize** 揀顯示邊啲欄。每個 list 可以有自己嘅欄（人、選項、文字、日期、數字），例如 Modelers 同 Project Manager。',
    ]),
    H3('一個 task'),
    UL([
        '撳一個 task 打開佢嘅視窗：標題、**Owners**、開始同到期 **Dates**、**Group**、**Priority** 同 list 自己嘅欄。**Mark complete** 就完成。',
        '**完成方式（Completion method）：** **OR** = 任何一個負責人完成就算完成；**AND** = 每個負責人都要完成自己嗰部分。',
        '**Sub-task：** 喺 **+ Add sub-task** 打字再按 Enter。好似 Lark 咁，sub-task 下面可以再有 sub-task，最多 5 層：打開個 sub-task 喺佢入面加，或者喺 List 撳行尾出現嘅 **+**。將一個 task 拖去另一個 task 標題嘅右半邊放手，就變成佢嘅 sub-task。刪一個 task 會連佢下面所有嘢一齊刪（**Ctrl+Z** 可以全部攞返）。',
        '**相連嘅 issue** 會顯示佢而家嘅狀態（Open、In progress、Resolved）。**+ Link an issue** 可以揀 project 嘅一個 issue。',
        '**檔案、sheet 同 3D 視圖：** 貼 OneDrive、SharePoint 或者 ACC 網址，或者喺 Sheets 或 3D 版撳 **+ Task**，將你睇緊嘅 sheet 或者視圖放落 task。放咗落 task 嘅 Revit 元件會顯示做 **Elements to change**。',
        '**留言：** @名 可以通知人；可以貼截圖或者夾檔案（每個最大 50 MB）。自己嘅留言有 **edit** 同 **delete**。',
        '**Follow** 之後 task 有改動會 email 你；**Share** 會傳去一個 chat；連結掣會 copy 佢嘅網址。',
        '▲ ▼ 掣，或者 **K** / **J**，去上一個／下一個 task。手機上面撳 **Back** 返去清單。',
    ]),
    H3('List 嘅成員'),
    UL([
        '**Owner**（改 list 設定同成員）、**Editor**（加同改 task）同 **Viewer**（只可以睇）。Site admin 睇到所有 list。',
    ]),
    H3('由 Lark import'),
    OL([
        '喺 Lark 打開個 task list，揀 **...** > **Export**（Excel）。',
        '喺 Tasks 用 **+** > **Import a Lark task list (.xlsx)** 開一個新 list，或者用 **...** > **Import from Lark (.xlsx) / CSV** 放入而家打開緊嘅 list。',
        'Group、sub-task、負責人、follow 嘅人、日期、完成狀態、優先次序、完成方式、milestone、Modelers 同 Project Manager 全部都會帶入嚟，每個 task 仲有一條連返去 Lark 嘅連結。',
        '再 import 同一個 export 會更新啲 task，唔會重複加。未有 account 嘅人名會照保留；account 開好之後用 **...** > **Match names to accounts**。',
    ]),
    H2('Board 白板'),
    P('**Board** 係每個 project 一塊共用白板，好似 Miro 咁：便利貼、文字、形狀、連接線、mind map、相同 frame，仲有範本可以由頭開始。Project 入面所有人會即時見到改動。喺頂部揀 project；用 board 清單開新、改名、複製或者刪除 board。'),
    H2('Messenger 訊息'),
    P('**Chat** 會打開 Messenger：團隊嘅對話，就喺佢哋講緊嘅工作隔籬。'),
    LABEL('Chat 嘅種類'),
    TABLE(['Chat', '係乜'], [
        ['Project channel', '每個 project 一個，project 所有人都喺入面。新 task、指派、完成、task 留言同新開或者改咗嘅 issue 會用卡片貼入嚟'],
        ['Topic', 'Project channel 入面講一樣嘢嘅分台（例如 Facade、MEP coordination、Site visits）。會列喺 channel 下面，亦會喺 channel 名下面做 tab 顯示：**# General** 就係 channel 本身'],
        ['Group', '任何一班人，由開 group 嘅人改名'],
        ['Direct message', '兩個人'],
        ['Task discussion', '你 follow 緊嘅 task 嘅留言，可以喺度直接回覆'],
    ]),
    UL([
        '頂部支筆開新 chat。喺 chat 上面撳右鍵（手機就㩒住佢）會有 **Details**、**Mark as read**、**New topic**（project channel）、**Leave**、**Import WhatsApp chat ...**、**Send chat link to WhatsApp**，有權刪嘅人仲有 **Delete chat**。',
        '**開 topic：** project channel 入面任何人都可以喺 channel 名下面嘅 tab 撳 **+ Topic**（或者 channel 選單嘅 **New topic**，或者支筆 > **Topic in a project channel**）。Channel 入面所有人都會加入去。',
        '**邊個可以刪 chat：** direct message 係兩個人任何一個（刪咗兩邊都冇）；group 係佢嘅 admin（開 group 嘅人）或者 site admin；project channel 同 topic 係 project 嘅 admin 或者 site admin。刪 channel 會連佢嘅 topic 一齊刪。',
        '**Chat info**（人仔掣）：描述、成員（加、移除、私訊）、**Pictures and files**、**Leave this chat** 同 **Delete this chat**。',
        '每一版頂部 **Chat** 上面嘅數字係未讀訊息；**@** 即係有人 mention 你。',
    ]),
    LABEL('打字'),
    UL([
        '**Enter** 係換行；撳 **Send** 掣先會發送（用鍵盤嘅話，**Ctrl+Enter** 都會發送）。',
        '可以貼或者拖截圖入嚟，或者用夾萬（📎）傳相同檔案，每個最大 50 MB。OneDrive、SharePoint 同 ACC 連結會顯示做卡片；影片連結會有播放卡，貼 OneDrive 或 SharePoint 嘅 **Embed** code 就可以喺 chat 入面直接播。',
        '**@** 一個人。**#** 一個 task、**!** 一個 issue、**$** 一張 sheet、**%** 3D model 或者儲存咗嘅視圖：一打就會彈出清單。**先揀 project**：清單最頂有一排 project 俾你揀（喺 project channel 會預先揀好嗰個 project）。夾萬隔籬嘅 **#** 掣會打開同一啲清單，有分頁。',
        '揀咗嘅項目會喺訊息入面變成一條有名嘅連結，撳就打開。',
        '🙂 可以加 emoji。',
        '**格式（Aa）：** 好似 Lark 咁，輸入框直接顯示發出去嘅樣。**Aa** 會顯示格式掣：**B**、**S**、**I**、**U**、編號同 bullet 清單、引用、連結、code 同 code block；**Ctrl+B**、**Ctrl+I**、**Ctrl+U** 同 **Ctrl+Shift+X** 對揀咗嘅字用。手機上面撳 **Aa** 之後格式掣會自己一行出現。轉去 WhatsApp 都會保留粗體、斜體同刪除線。',
        '**輸入框下面嘅掣：** **Aa**、🙂 emoji、**@** 人、**#** task、issue、sheet 或者 3D 視圖（喺框入面顯示做 chip）、夾萬、**+** 同 **Send**；**Send** 永遠喺畫面入面，手機都係。',
        '**+ 掣：** **Poll**、**Event / meeting**、**Task**，或者連結一個 task、issue、sheet 或者 3D 視圖。',
    ]),
    LABEL('投票、活動同 task'),
    UL([
        '**Poll（投票）：** 一條問題，2 至 10 個選擇；想嘅話剔 **Allow more than one answer**、**Anonymous** 或者揀截止日期。撳一個選擇就投票，再撳就取消。寫嘅人可以 **Close poll**（亦可以重開）。',
        '**Event（活動）：** 標題、日期、時間（或者 **All day**）、地點同 Teams 連結。Chat 入面所有人都會收到邀請（mail 設定好嘅話仲會有 email），可以答 **Going**、**Maybe** 或者 **Can\'t go**。**Add to calendar (.ics)** 可以放入 Outlook、Google 或者手機日曆。寫嘅人可以 **Change** 或者 **Cancel event**；chat 會收到通知。',
        '**Task：** 揀 task list 同 group（呢個 project 嘅排先）、負責人（呢個 chat 嘅人排先）、到期日同優先次序。Task 會放入個 list，佢張卡片會出現喺 chat。喺任何訊息撳 ⋯ More > **Make a task** 都一樣，訊息會變成描述，@mention 咗嘅人做負責人，仲有條連結返去嗰條訊息。',
    ]),
    LABEL('一條訊息'),
    UL([
        '滑鼠移到訊息上面（手機就撳一下）：🙂 **React**、↩ **Reply**、✏ **Edit**（自己嘅訊息）同 ⋯ **More**：**Copy**、**Pin**、**Make a task**、**Forward to another chat**、**Send to WhatsApp**、**Copy link to this message** 同 **Delete**（自己嘅訊息）。',
        '**Edit** 直接喺原位改：**Ctrl+Enter** 儲存，**Esc** 取消；其他人會見到「(edited)」。**Edit** 同 **Delete** 只限發訊息嘅人（chat 嘅 admin 同 site admin 都唔得）；其他人會見到「message deleted」。',
        '**Pin 訊息：** chat 入面任何人都可以 pin 訊息，每個 chat 最多 100 條。Chat 名下面嗰條會顯示最新 pin 嘅一條；撳佢就去睇嗰條訊息，再轉去下一條；**All** 會列晒出嚟，可以 **unpin**。',
        '**Reaction** 會喺訊息下面顯示，連數目；撳一下就加或者攞走你嘅。',
        '發唔到嘅訊息會留低，有 **send again** 俾你再試。',
    ]),
    LABEL('WhatsApp'),
    UL([
        '**轉出去：** 訊息上面嘅 **Send to WhatsApp** 會將文字、連結同檔案傳出去。手機上面相片會原本咁經分享選單傳過去；電腦就會打開 WhatsApp Desktop 或者 WhatsApp Web。',
        '**Copy 咗嘅訊息：** 喺 WhatsApp copy 幾條訊息，貼入輸入框，會問你係咪變成一個「From WhatsApp」引用。',
        '**匯出成個 chat：** 喺 WhatsApp 打開個 chat > **More** > **Export chat**，將 .zip（有相）或者 .txt 傳俾自己。然後喺 chat 選單揀 **Import WhatsApp chat ...**：啲訊息會變成一個引用，相片放返喺原本嘅位置。',
        '**Android：** 將 viewer 安裝做 app 之後，喺 WhatsApp 撳 **Share** > **LWK Viewer**，再揀 chat。（iPhone 唔支援：用 copy 貼上，或者匯出。）',
        '同 WhatsApp 之間冇自動雙向同步。',
    ]),
    H2('Calendar 日曆'),
    P('**右撳某一日**（手機㩒住）可以喺嗰日加 **event**（全日）、**meeting**（10:00 開始，揀邀請邊個 chat）或者一個嗰日到期嘅 **task**。'),
    P('**Calendar** 按日期顯示你就嚟要做嘅嘢：Messenger 入面發嘅**會議**（連你嘅回覆）、**你嘅 task** 嘅到期日，同**派咗俾你嘅 issue** 嘅到期日。'),
    UL([
        '電腦係月曆，手機係清單（**Month** / **List**）。剔格可以顯示或者隱藏會議、task 同 issue。**‹ ›** 同 **Today** 轉月份；手機可以掃。',
        '撳一項睇詳情，再打開個 chat、task 或者 issue。回覆會議要喺佢個 chat 入面。',
        '**+ Event：** 揀一個 chat，活動表格就喺嗰度打開，chat 入面所有人都會被邀請。',
        '**Add to Outlook：** **Open in Outlook on this PC** 會令 Outlook 訂閱你嘅日曆（揀 **Yes**），或者 copy 個地址，用 Outlook 嘅 **Add calendar > From Internet**。之後 Outlook 會喺你自己嘅日曆隔籬顯示，並自己更新。Outlook 網頁版同手機版要 viewer 喺互聯網上連得到先得。',
        '個地址係你自己嘅：唔小心分享咗就撳 **Make a new address**（舊嗰個會停用）。',
    ]),
    H2('通知同 app'),
    P('有新訊息唔使 refresh 都會通知你，viewer 仲可以裝成一個 app。'),
    UL([
        '**開住任何一版 viewer 嘅時候**（任何一版、背景嘅分頁，或者個 app）：新訊息會喺 Windows、Mac 同 Android 彈通知；撳一下就打開嗰個 chat 去到嗰條訊息。你睇緊嗰個 chat 就唔會彈。分頁標題會顯示未讀數，例如 **(3) LWK Viewer**，app 個 icon 都會有。',
        '**頂部嘅鈴**：撳 **Turn on notifications**（瀏覽器會問一次），再揀 **Every message**（所有訊息）、**@mentions and direct messages**（只係 @你 同私訊）或者 **Nothing**（唔通知）。',
        '**某個 chat 靜音：** Chat info > **Mute notifications**。靜咗音嘅 chat 有人 @你 都照通知。',
        '**唔止訊息：** 有 task 派咗俾你、有人喺 task 或者 issue 度 @你、有 issue 派咗俾你或者你嘅 query 有人答、你嘅 task 就快到期，都會通知你。鈴入面嘅 **For you** 清單列出最近嘅（紅色數字係未睇嘅）；撳一項就打開，**Mark all read** 清咗個數字。',
        '**裝 app：** 鈴 > **Install the app**（Edge、Chrome），或者網址列右邊嘅安裝 icon。Android：選單 > **Add to Home screen**。iPhone／iPad：Safari > 分享 > **加至主畫面**。App 會用自己嘅視窗打開，右撳 icon 有 Chat、Tasks、Calendar、Folders 同 Projects 捷徑。',
        '**冇開任何一版都收到（push）：** 鈴 > **Turn on for this device**。要用 viewer 嘅 **https** 地址開先得（問你嘅 admin）。之後就算 app 閂咗，部手機或者電腦都會收到訊息。',
        '**iPhone／iPad：** 先喺 Safari > 分享 > **加至主畫面**，再由主畫面個 icon 打開；然後喺鈴度開通知、撳 **Turn on for this device**，再撳 **Send a test**。收唔到嘅話，會講埋原因（例如 server 連唔到 Apple）。Server 更新之後，請關一次再開一次 push。',
    ]),
    H2('外觀、連結同新功能'),
    P('幾樣小嘢，等你喺 viewer 入面易啲搵路，又易啲同人分享。'),
    UL([
        '**深色模式（Dark mode）：** 鈴 > **Look** > **Dark**。**Auto** 跟你部電腦或者手機（佢設咗夜晚轉深色就跟住轉）；**Light** 係平時嘅樣。每部電腦、每部手機各自記住。圖則、PDF、文件預覽同白板會保持白色（當係紙）；3D 背景會變深灰，除非你喺 Display 揀咗自己嘅顏色。',
        '**新功能（What\'s new）：** 每次更新之後會彈一張小卡，講有咩改咗，只出一次。撳 **Got it** 收埋；隨時都可以喺鈴 > **What\'s new in the viewer** 睇晒成個列表。',
        '**複製連結（Copy link，🔗 掣）：** 複製一個網址，可以貼落 chat 或者 email。只有 project 入面嘅人先開到。',
        '**一張 sheet：** sheet 工具列嘅 🔗。**一個 issue：** issue 頂部嘅 🔗（2D 或 3D）。**一個 project：** Projects 版 project panel 嘅 🔗。**一個 3D 視角：** 3D 頂部 **Fit** 隔籬嘅 🔗，會複製返一模一樣嘅視角 - 鏡頭、section box 或 plane、樓層、顯示模式同隱藏咗嘅元件 - 開嘅人會見到一樣嘢。',
        '**可以摺埋嘅部分：** 喺 project panel（Projects 版）、Admin 版或者 3D 左邊 panel，撳個標題就摺埋或者打開。viewer 會記住你摺埋咗邊啲。',
        '**列表記住你去到邊：** Folders 會重新打開你之前喺樹度開咗嘅 folder；sheet 列表同 chat 列表會將你而家嗰個保持喺眼前。',
        '**列表載入緊嘅時候** 會見到灰色嘅佔位行，話你知內容會喺邊度出。',
    ]),
    H2('還原（Undo）'),
    UL([
        '**Ctrl+Z**（Mac 係 Cmd+Z）還原上一個改動；**Ctrl+Y**（或者 Ctrl+Shift+Z）重做。底部會顯示還原咗乜嘢，有 **Redo** 掣。',
        '**Tasks：** 改欄、Kanban 搬卡、List 拖行、Gantt 改日期、開新 task，同刪除 task（連埋佢嘅 sub-task）。',
        '**Messenger：** 刪咗嘅訊息（自己嘅，一日之內）、修改、pin 同 reaction。',
        '**Folders：** 刪除、改名、搬、上載同開新 folder。',
        '喺輸入框打緊字嘅時候，Ctrl+Z 照舊還原打字。Sheets 同 3D 版嘅 markup 有自己嘅 undo。',
    ]),
    H2('Folders 檔案夾'),
    P('喺左邊 folder 樹右撳一個 folder（或者用 folder 嘅 ⋯），可以 **New folder here**（喺度開新 folder）、改名、**Move to ...**、加星、Pin、copy 連結同刪除。'),
    P('**唔使下載都睇到：** 撳 PDF、相、片、文字檔，或者 **Word、Excel、PowerPoint**，就會喺清單隔籬打開。Server 裝咗 LibreOffice（問你嘅 admin）嘅話，Office 檔案會同喺 Office 入面一模一樣；未裝就用簡單啲嘅方式顯示 Word 同 Excel，PowerPoint 要下載。'),
    UL([
        '**俾文件多啲位：** 清單左上角嘅 **☰** 收埋／打開左邊 folder 欄（會記住）。預覽入面嘅 **⤢** 連 folder 同檔案清單都收埋，文件用晒成個闊度；再撳一次或者 **Esc** 就返嚟。拖預覽嘅左邊邊位可以拉闊。',
        '**成版睇晒：** 喺網頁度顯示嘅 Word 同 Excel 一開就係 **Fit**：最闊嗰版（橫向都得）啱啱好放得落預覽闊度，電腦同手機都係。**−**、**+** 縮放；**Fit** 返原。PDF 一打開就係頁闊。',
        '**手機同平板**（打直或者打橫）：文件會全屏打開，PDF 同轉換咗嘅 Office 檔案一頁接一頁，可以向下碌晒全部頁；兩隻手指 pinch 或者用 **−** / **+** 縮放。**☰** 打開 folder 欄，撳旁邊空位就收返。',
        '**Admin 用 - 喺 server 裝 LibreOffice**（Ubuntu）：`sudo apt-get install -y --no-install-recommends libreoffice-writer libreoffice-calc libreoffice-impress fonts-noto-cjk fonts-liberation fonts-crosextra-carlito fonts-crosextra-caladea`，然後重開 viewer service。Writer、Calc、Impress 三個都要裝：淨係得 libreoffice-core 嘅話，網頁會話「cannot read this kind of file」。大文件第一次要等一陣，之後有 cache，即刻開到。',
    ]),
    P('**Folders** 將每個 project 嘅檔案放喺 server 上面一個 folder，好似 ACC Docs 或者共用 drive 咁。喺左上角揀 project。'),
    P('**00 BIM**（🔒，永遠排第一）放住 viewer 已有嘅嘢，自動更新：**2D Sheets**（由 Revit 出嘅 sheet，用編號同名稱命名，同埋喺 Sheets 頁上載嘅 PDF set）同 **3D Models**（喺 3D 頁打開；IFC 檔案 - IFC project 同顧問 model - 可以下載）。Project 入面所有人都可以打開同下載，但冇人可以加、改名、搬或者刪。有幾個部分嘅 project，每部分一個 folder。'),
    UL([
        '**瀏覽：** 左邊嘅 folder 樹、頂部嘅路徑，或者 **Search this project\'s files** 搜尋。雙擊 folder 打開；撳 PDF、相或者片就預覽。',
        '**上載：** 將檔案，甚至成個 folder 拖落版面（或者拖落清單入面某個 folder），或者撳 **Upload**。**+ Folder** 開新 folder。',
        '**檔案嘅 ⋯**（或者右撳）：預覽、下載、**Add to the Sheets page**（PDF）、**Star**（加星）、**Pin for everyone**（project admin）、copy 連結、改名、**Move to ...** 同刪除。將檔案拖落 folder 就搬；揀咗檔案可以用 **Delete** 同 **F2**。',
        '**Pinned** 係 project admin 幫大家 pin 嘅重要文件；**Starred** 係你自己加星嘅。**Recent** 列出最新嘅檔案。',
        '**刪除：** 上載嗰個人，或者 project admin。刪咗嘅嘢會去 **Recently deleted**，可以放返原位；**Ctrl+Z** 都可以即刻攞返。',
        '**Folder 範本（project admin）：** 右上 ⋯ > **Save these folders as a template**，將呢個 project 嘅 folder 結構（唔包檔案）用個名儲起。喺另一個 project 用 **Lay out folders from a template**，就會開返佢未有嘅 folder；乜都唔會刪。',
        '**放去 Sheets 版：** PDF 嘅 ⋯ > **Add to the Sheets page**，每一頁變成一張 sheet，放喺自己一個 set（揀 set 名同 sheet 編號），即刻可以 markup 同開 issue。',
        '用其他方法（例如 Windows Explorer）放入 server 上面嗰個 folder 嘅檔案，呢度都會見到。',
    ]),
]
