# 廣東話版 第三部分：Sheets (2D) 到 Walking through the model

from blocks import *

PART = [
    H2('Sheets：2D 圖則'),
    P('Sheets 版顯示每張 publish 咗嘅 sheet，係真正嘅 PDF，搜尋得到，即刻可以 markup；markup 自己會儲存，冇 Save 掣。'),
    H3('搵 sheet'),
    UL([
        '左邊嘅 **Sheets** 清單顯示 sheet 編號同名。「x/y mapped」即係張 sheet 上面有幾多個 view 連咗去 3D model。',
        '撳一張 sheet 就打開。Viewer 會記住你上次打開嘅 sheet。',
        '**Search all sheets** 搵 sheet 編號、名，同埋圖上面印住嘅任何字（房名、note、grid 編號）。搵到嘅會喺 sheet 上面 highlight。一個 project 第一次搜尋可能要等一陣，因為要讀晒啲圖。',
        '**Page Down / Page Up** 去下一張或者上一張 sheet。',
        '要加外面嘅 PDF（顧問嘅圖、草圖），用 **PDF** upload 掣。佢會喺清單顯示做「Imported 2D only」，撳佢個 **✕** 就可以移除。',
    ]),
    H3('喺 sheet 上面移動'),
    TABLE(['動作', '滑鼠', 'iPad / 觸控'], [
        ['Zoom', '碌滑鼠轆（圍住游標 zoom）', '兩隻手指捏'],
        ['Pan', '㩒住中間掣，或者用 **Pan** 工具（H）', '兩隻手指；用過 Apple Pencil 之後，一隻手指就 pan'],
        ['成張 sheet', '**Fit**', '**Fit**'],
        ['轉張紙', '工具列嘅 Rotate 掣', '一樣'],
        ['選單', '撳右鍵', '㩒住'],
        ['Undo / redo', 'Ctrl+Z / Ctrl+Y', '兩隻手指 tap / 三隻手指 tap'],
    ]),
    H3('Sheet 有用嘅工具'),
    UL([
        '**Split** 喺隔籬打開第二張 sheet，有自己嘅 zoom。',
        '**Links** 將 section 標記、callout 同 elevation 標記變成連去佢哋 sheet 嘅連結；**← back** 返去。',
        '**Compare** 顯示同一張 sheet 之前 upload 嘅版本、另一張 sheet，或者你電腦入面一個 PDF 有乜唔同：紅色 = 刪咗，綠色 = 加咗。**N / Shift+N** 喺改動之間跳。',
        '**2D + 3D** 喺 sheet 隔籬打開 3D model。揀 **Stand there** 或者 **Look at**，然後撳 plan：3D 視圖就會去嗰個位。Plan 上面有個「你喺度」標記跟住 3D 鏡頭；剔 **Follow** 就會一直睇住佢，你喺唔同樓層之間行嘅時候會自動轉 plan。只有 plan view 有用，section 同 elevation 唔得。',
    ]),
    H3('Markup 工具'),
    TABLE(['類別', '工具'], [
        ['形狀', 'Rect、Circle、Line、Arrow、Cloud、Polyline、Polygon'],
        ['手寫', 'Pen（一筆畫完之後停定唔郁，就會變成直線、圓或者長方形）、Highlighter'],
        ['文字', 'Text、Text box、Callout'],
        ['印章', 'APPROVED、APPROVED AS NOTED、REVISE & RESUBMIT、REJECTED、REVIEWED、FOR INFORMATION、VOID（會簽上你個名同時間）'],
        ['量度', 'Measure、Dimension、Area、Angle（用 **1:** 格入面嘅比例；空白就用 view 自己嘅比例）'],
        ['其他', 'Snip（將一個範圍 copy 做圖片；亦可以貼圖入嚟）、Select text、Eraser、Match properties、Select、Pan'],
    ]),
    UL([
        '**Polyline / Polygon：** 撳啲點，然後按 Enter、double-click 或者 **✓ Finish**。Backspace 刪最後一點。',
        '**Style bar：** Layer、線／填色／文字顏色、Opacity、Weight（紙上 mm）、線 Type、Font、Size（字高 mm）、Align。',
        '**改 markup：** 揀一個 markup 就可以搬、改大細或者改樣式；R / Shift+R 轉 90°；Ctrl+C / Ctrl+V copy 同貼（貼去另一張 sheet 會喺同一個位置）；Delete 刪除。',
        '**Comment 定 Issue：** 頂部嘅 **Comment / Issue** 掣決定畫完 markup 之後做乜。喺 **Issue** 模式會即刻彈出 **Raise issue** 視窗。Comment 之後都可以用 **Issue** 或者右鍵 **Raise issue** 變成 issue。',
        '**Layer：** markup 放喺 layer 上面（預設「General」）。Admin 可以鎖 layer 或者唔俾某啲人睇到。眼仔掣會隱藏所有 markup。',
    ]),
    H3('Export'),
    UL([
        '**PDF**（download）export 呢張 sheet、所有有 markup 嘅 sheet，或者全部 sheet；markup 可以係 **Editable**（Bluebeam、Acrobat 或 PDF-XChange 用嘅真 PDF comment）或者 **Flattened**，100、150 或 200 dpi，可以喺最尾加 issue 報告。',
        '**JSON**（download / upload）儲存或者載入所有 comment 同 issue，用嚟 backup 或者搬去另一個 project。',
        '**BCF** export sheet 嘅 issue 俾 Revit 或 Navisworks（睇「Issue 同 BCF」）。',
    ]),
    H2('3D：四圍睇'),
    P('3D 版嘅滑鼠用法同大部分 BIM viewer 一樣：右掣轉、中間掣 pan、轆 zoom、左掣揀。'),
    H3('滑鼠、觸控同鍵盤'),
    TABLE(['動作', '滑鼠', 'iPad / iPhone'], [
        ['Orbit（轉）', '㩒住右掣拖', '一隻手指'],
        ['Pan', '㩒住中間掣（轆）拖', '兩隻手指'],
        ['Zoom', '碌滑鼠轆（向住游標）', '兩隻手指捏'],
        ['對準一個面', 'Double-click 佢', 'Double tap'],
        ['揀一個元件', '左掣撳', 'Tap'],
        ['設定轉嘅中心', '右鍵撳唔好拖，或者右鍵選單 **Set orbit centre here**', '-'],
        ['動作選單', '撳右鍵', '-'],
        ['喺一個位開新 issue', '**Add issue**，然後撳', '㩒住（0.6 秒）'],
        ['上一層／下一層', 'Page Up / Page Down', 'Floor plan 清單'],
        ['取消量度或者行', 'Esc', 'Stop 掣'],
    ]),
    P('用滑鼠嘅話，你一放手畫面就停喺嗰度；用手指會滑多少少，同其他平板 app 一樣。'),
    H3('右鍵選單'),
    P('喺元件上面：**Set orbit centre here**、**Zoom to this element**、**Isolate**、**Hide**、**Show all**、**Walk from here**、**Add issue here**、**Section on this face**、**Square section box to this face**、**Turn section on/off**、**Measure**、**Save view...**、**Fit model**。喺空位：Show all、Turn section on/off、Measure、Save view...、Fit model。'),
    H3('View cube 同鏡頭'),
    UL([
        '撳 cube 嘅一個**面**睇嗰個方向，撳一條**邊**睇兩個面之間，撳一個**角**睇 isometric。拖個 cube 可以轉。下面個圈顯示北面。',
        '屋仔掣返去 3D 全景。**Fit** 將所有載入咗嘅 model 放晒入畫面。',
        '**Perspective / Parallel** 轉投影方式（plan 永遠係 parallel）。',
        '**Set front：** 撳一幅牆話俾 cube 知呢棟樓邊面係「Front」；**World** 返去世界軸。',
    ]),
    H3('樓層'),
    UL([
        '**Floor plan** 下拉選單列出 **Whole building** 同由上至下每一層。',
        '揀一層就會由嗰層樓面以下 0.5 m 切到以上 1.2 m，再由上面直望落去，好似 Revit 嘅 plan 咁。',
        '**Page Up / Page Down** 上落一層；**Whole building** 返去成個 3D model。',
        '**Drawing** 將嗰層嘅 plan sheet 鋪喺 model 上面，等你對比圖同 model。',
    ]),
    H3('Models panel'),
    UL([
        '每個 model（主 model 同每個 link）一個剔格。唔剔就會隱藏個 model，慳返記憶體；**All on / All off** 一齊開關，視圖唔會變。',
        'Model 隔籬嘅 **▸** 顯示佢嘅大細同副本數目，仲有 **Compare with previous export**，睇上次 publish 之後加咗、改咗或者刪咗乜。',
        '**Apply link transforms**（開咗）會將 link 放喺 Revit 入面嘅位置。',
        '**Light mode (phones, tablets)** 只會喺你望緊嘅附近載入重複嘅標準層。手機同平板預設開咗。',
        '每個 panel 嘅標題（Models、Section、Measure 等等）撳一下就收埋，下次都會保持收埋。',
    ]),
    H2('3D：揀、搵同顯示'),
    P('撳任何元件就睇到佢係乜；用 Model browser 可以按名、type、樓層或者 property 搵元件。'),
    H3('Selection panel'),
    P('撳一下會顯示元件嘅 **Model**、**Category**、**Family / type**、**Level**、**Revit id**（ElementId）、**UniqueId**、**IFC GUID**、撳中嘅 **Point**（x、y、z，單位米）同 **Shared E,N,Z**（測量座標），跟住係佢所有 Revit parameter，分組可以收埋。'),
    UL([
        '**Copy Revit ID** copy ElementId；喺 Revit 用 **Manage > Select by ID** 貼上，就會揀中同一個元件。**Show in Revit** 叫 LWK add-in 喺 Revit 揀佢（睇「Revit 元件」）。**+ Task** 將個元件放落一個 task。',
        '**Isolate** 只顯示揀咗嘅元件。**Hide** 隱藏佢哋。**Show all** 全部返嚟。有個數字顯示隱藏咗幾多個。',
        'Hide 同 isolate 只會改你自己嘅視圖，乜都冇刪到。',
    ]),
    H3('Elements panel'),
    P('每個 category 一個剔格（Walls、Floors and slabs、Columns、Windows、Doors、Furniture、Railings...），有數目。唔剔一個 category 就隱藏佢；**Show all** 全部開返。你揀咗乜會記住。'),
    H3('Model browser'),
    UL([
        '一個樹狀清單：**model › category › family / type › 元件**。撳一行打開佢同揀成組；撳一個元件會 highlight 同 zoom 埋去。',
        '**Search names, types, levels, properties**：普通字會對 name、category、family、type 同 level。用 **property:value** 對一個 parameter，例如 Fire Rating:2 hr 或者 Mark:D101。',
        '**Select** 將搵到嘅上色，**Isolate** 只顯示佢哋，**Zoom** 放晒入畫面。**Select** 之後，頂部嘅 **+ Task** 會將所有揀咗嘅元件放落 task 做「Elements to change」，**Copy Revit ID** 會 copy 晒佢哋嘅 id。',
        'Browser 用喺 fast 3D 格式 publish 嘅 model（即係正常 Publish to Viewer 出嚟嘅）。',
    ]),
    H3('Display'),
    TABLE(['模式', '用嚟'], [
        ['**Shaded**', '正常睇，用 model 自己嘅顏色'],
        ['**White**', '乾淨、冇顏色，啱 review 同截圖'],
        ['**X-ray**', '透過牆同樓板睇到入面'],
    ]),
    P('**Display** panel 仲可以設定背景顏色、地面（開關同顏色）同 grid。'),
    H3('Saved views'),
    UL([
        '**Save**（或者右鍵 **Save view...**）會連名同縮圖儲存鏡頭、section 同隱藏咗嘅元件。Saved view 成個 project 都睇到。',
        '撳一個 saved view 返去嗰度；**✕** 刪除。',
        '由 3D 去 Sheets 再返嚟，你上次嘅 3D 視圖會原封不動咁返嚟。',
    ]),
    H2('Section box、section plane 同 floor plan'),
    P('用 section box 將棟樓一部分切開，用 section plane 沿住任何一個面切；切到嘅實體會顯示橙色 hatch，好似圖則咁。'),
    H3('Section 工具'),
    TABLE(['掣', '做乜'], [
        ['**Box**（剔）', '開 section box，圍住成個 project'],
        ['**Plane**', '撳一個面：model 就喺嗰個面切開'],
        ['**Align**', '撳一幅牆：個 box 會轉到同嗰幅牆對正'],
        ['**Flip**', '留 section plane 另一邊'],
        ['**Reset**', '移除所有切面'],
        ['**Solid fill on the cut**', '切到嘅牆、樓板同柱會顯示橙色 hatch（預設開）'],
        ['**Plan look for floor plans**', '喺 floor plan 入面，表面淡啲，下面嘅樓層會淡出（預設開）'],
    ]),
    P('Floor plan 下拉選單（睇「3D：四圍睇」）就係一層樓現成嘅 section box。'),
    H3('移動切面'),
    UL([
        'Box 每個面都有一粒**有短柄嘅彩色點**：紅色 X、綠色 Y、藍色高度。單一 section plane 係橙色點。',
        '**滑鼠：** 移到一粒點上面，或者切面嘅邊（個面會變橙色），然後拖。切面只會沿住自己嘅方向郁。',
        '**iPad / iPhone：** 一隻手指拖粒點。兩隻手指永遠係郁視圖、唔會郁切面，所以開住 section 都可以隨便捏同轉。',
        '喺電腦上面，切面停定之後會有啡色線描出切口嘅邊。手機同平板只顯示 hatch。',
    ]),
    H3('方便嘅快捷'),
    UL([
        '右鍵撳一幅牆或者樓板：**Section on this face** 就喺嗰度切；**Square section box to this face** 將個 box 對正佢。',
        '右鍵撳空位：**Turn section on/off**。',
    ]),
    H2('喺 3D 量度'),
    P('每個量度點都會 snap 去真實嘅角、邊或者中點，個 label 會話你知係邊種，你就知個數信唔信得過。'),
    H3('點樣量'),
    OL([
        '撳頂部嘅 **Measure**（或者右鍵 **Measure**），揀 **Distance**、**Angle** 或者 **Area**。',
        '將游標移過 model。彩色點同 label 會顯示下面 snap 到乜。',
        '撳第一點，再撳下一點。距離會跟住你郁即時更新，仲有佢嘅 **plan** 同 **height** 部分。',
        '按 **Esc** 放棄一個唔小心開始咗嘅量度。',
    ]),
    TABLE(['模式', '點數', '結果'], [
        ['**Distance**', '2', '長度（1 m 以下用 mm，否則用 m），仲有 plan 同 height 部分'],
        ['**Angle**', '3', '中間嗰點嘅角度'],
        ['**Area**', '3 至 64', '多邊形面積（m²）'],
    ]),
    H3('Snap'),
    TABLE(['顏色', 'Snap', '意思'], [
        ['紅色', 'corner', '元件嘅一個頂點，或者 section 入面切口嘅角'],
        ['紫色', 'midpoint', '一條邊嘅中間'],
        ['綠色', 'perpendicular', '由你上一點到一條邊嘅垂直線落腳點'],
        ['藍色', 'edge', '一條邊上面任何一點'],
        ['灰色', 'surface', '附近冇特徵：面上面嘅點（冇咁準）'],
    ]),
    UL([
        '每次 snap 到新嘢都會有個圈散開（手機會震），等你知捉到咗。',
        '喺 floor plan 或者 section 入面，snap 會跟住切口輪廓，所以喺 plan 可以量牆到牆。',
        '曲面係由好多細平面組成，所以暫時未有切線或者弧心 snap。',
    ]),
    H3('Straight 同其他掣'),
    UL([
        '**Straight** 令下一點同上一點沿 X、Y 或者高度成一直線，量真正正交嘅距離。㩒住 **Shift** 就只係下一點轉換。',
        '**Undo** 刪最後一點，**Clear** 刪晒所有量度。',
        '**Keep** 將量好嘅距離儲存做 dimension，project 所有人都睇到。**Dimensions** 剔格顯示或者隱藏 keep 咗嘅 dimension，每個都可以撳 **✕** 刪除。',
    ]),
    H2('喺 model 入面行'),
    P('Walk 模式將你放喺棟樓入面眼睛嘅高度，跟住樓板、樓梯同斜路行。'),
    P('**開始：** 撳 **Walk**，然後撳一塊樓板（撳牆會將你放喺牆前面嘅樓板）。或者右鍵撳一個位揀 **Walk from here**。開始行會熄 floor plan 同 section box。'),
    TABLE(['動作', '鍵盤／滑鼠', 'iPad / iPhone'], [
        ['向前／向後', 'W / S 或者 ↑ / ↓', '畫面上嘅控制板'],
        ['打側行', 'A / D', '畫面上嘅控制板'],
        ['轉身', '← / →，或者用滑鼠拖', '用手指拖，或者控制板'],
        ['望上望落', '用滑鼠拖', '用手指拖'],
        ['快啲', '㩒住 Shift（3 倍速）', '-'],
        ['向前或者向後一步', '碌滑鼠轆', '-'],
        ['上一層／下一層', 'Page Up / Page Down', '-'],
        ['升／降（Gravity 熄咗）', 'E / Q', '-'],
        ['停', 'Esc 或者 **Stop**', '**Stop**'],
    ]),
    P('**Walking panel 設定**（會記住）：'),
    UL([
        '**Eye** 眼睛高度，0.8 至 3 m（預設 1.6 m）。',
        '**Speed** 速度，0.5 至 8 m/s（預設 1.5 m/s）。',
        '**Gravity**（開）：企喺樓板上面，行得上樓梯同斜路，唔理檯咁高嘅級。',
        '**Walls block**（熄）：唔俾你穿牆。Model 入面啲門係閂住嘅，所以開咗呢個連門口都會擋住。',
    ]),
    P('喺 Sheets 版用 **2D + 3D** 加 **Walk**，就可以喺 3D 行，隔籬嘅 plan 會顯示你喺邊。'),
]
